### ISSUE TITLE
Pagination not working properly?

### ISSUE THREAD

**Issue by glikson** [telefonicaid/fiware-orion#1647] opened 2016-01-08 08:24 UTC
I am experiencing a strange behavior of Orion in FIWARE Lab. Between two queries with the only difference being the entity type ("santander:device" versus "bikerenting"), one is working properly, and the other is ignoring "limit" (probably also "offset") and returning "Count: 0" in details. The queries are:

echo '{"entities": [{"type":"santander:device","isPattern":"true","id": ".*"}],"attributes":[]}' | curl -X POST orion.lab.fiware.org:1026/v1/queryContext?limit=1&offset=0&details=on -s -S \
--header 'Content-Type: application/json' --header 'Accept: application/json' --header "X-Auth-Token: $AUTH_TOKEN" -d @- | python -mjson.tool

echo '{"entities": [{"type":"bikerenting","isPattern":"true","id": ".*"}],"attributes":[]}' | curl -X POST orion.lab.fiware.org:1026/v1/queryContext?limit=1&offset=0&details=on -s -S \
--header 'Content-Type: application/json' --header 'Accept: application/json' --header "X-Auth-Token: $AUTH_TOKEN" -d @- | python -mjson.tool

Here are the version details:
$ curl -X GET orion.lab.fiware.org:1026/version -s -S --header "X-Auth-Token: $AUTH_TOKEN"

```
    <orion>
      <version>0.26.1</version>
      <uptime>24 d, 20 h, 21 m, 34 s</uptime>
      <git_hash>93376583fbb6c8dd68b80b5bac436bf03f7d8358</git_hash>
      <compile_time>Wed Dec 9 11:45:27 CET 2015</compile_time>
      <compiled_by>fermin</compiled_by>
      <compiled_in>centollo</compiled_in>
    </orion>
```

**Comment by fgalan** [comment] 2016-01-08 14:52
This behaviour is due to Context Provider (CPr) forwarding. Note that in the case of "santander:device" all the information is local to CB, while in the case of "bikerting", there is no local information and all is retrieved from a CPr.

```
> db.entities.count({"_id.type": "santander:device"})
1203
> db.entities.count({"_id.type": "bikerenting"})
0
> db.registrations.count({"contextRegistration.entities.type": "bikerenting"})
4
> db.registrations.count({"contextRegistration.entities.type": "santander:device"})
0
```

Mixing pagination with CPr has some problems which solution is not clear (have a look to the "root" issue on pagination with CPr: https://github.com/telefonicaid/fiware-orion/issues/847). As you can see, currently there are two ideas on the table (any other suggestion? ;) but it is not clear which one to adopt at the end (both involve extra cost).

**Comment by fgalan** [comment] 2016-01-08 14:52
The present issue could be considered as a "child" of #847, i.e. once #847 got solved, the present issue will probably solved.

**Comment by glikson** [comment] 2016-01-08 22:22
Thanks. So, how can I retrieve data associated with such a query? Is there some sort of workaround? E.g., can I retrieve details about the CPr and access it directly? Moreover, a subscription that I registered for bikerenting doesn't seem to be working either. Is it because of the same issue?

**Comment by fgalan** [comment] 2016-01-11 13:43
The workaround is to use the same queries, but assuming that the pagination parameters will be ignored. Actually, the second query you mentions works ok (returning 22 entities, at the moment of writting this).

Regarding subscripitions, CB doesn't know when informatino change in CPr (and pooling them for changes is not efficient). Thus, by the moment onchange subscriptions work only with entities that are local to the CB.

**Comment by fgalan** [comment] 2023-06-09 11:16
> The present issue could be considered as a "child" of #847, i.e. once #847 got solved, the present issue will probably solved.

Based on this, as issue #847 was closed by PR https://github.com/telefonicaid/fiware-orion/issues/4149 we are going to close this issue. If we are wrong and it is still not working, please tell us about it (with the detailed steps to reproduce the problem), please.

**Closed by fgalan** 2023-06-09 11:16 UTC
Labels: bug, P5
