### ISSUE TITLE
Installation issues with YUM and RPM

### ISSUE THREAD

**Issue by mchoeti** [telefonicaid/fiware-orion#3127] opened 2018-03-08 12:30 UTC
There are some installation issues. I tried to install it via yum (recommended).

- First i added the repo
- yum install contextBroker

error message:
```
Error: Package: contextBroker-1.7.0-1.x86_64 (fiware)
           Requires: libboost_regex-mt.so.5()(64bit)
Error: Package: contextBroker-1.7.0-1.x86_64 (fiware)
           Requires: libboost_system-mt.so.5()(64bit)
Error: Package: contextBroker-1.7.0-1.x86_64 (fiware)
           Requires: libboost_thread-mt.so.5()(64bit)
Error: Package: contextBroker-1.7.0-1.x86_64 (fiware)
           Requires: libgnutls.so.26(GNUTLS_1_4)(64bit)
Error: Package: contextBroker-1.7.0-1.x86_64 (fiware)
           Requires: libboost_filesystem-mt.so.5()(64bit)
Error: Package: contextBroker-1.7.0-1.x86_64 (fiware)
           Requires: libgnutls.so.26()(64bit)
```
	 
Then i gave the RPM installation a try:

- got the link as example:  
https://forge.fiware.org/frs/download.php/1802/contextBroker-1.7.0-1.x86_64.rpm
- did the installation ==> failed

```
error: Failed dependencies:
        libboost_filesystem-mt.so.5()(64bit) is needed by contextBroker-1.7.0-1.x86_64
        libboost_regex-mt.so.5()(64bit) is needed by contextBroker-1.7.0-1.x86_64
        libboost_system-mt.so.5()(64bit) is needed by contextBroker-1.7.0-1.x86_64
        libboost_thread-mt.so.5()(64bit) is needed by contextBroker-1.7.0-1.x86_64
        libgnutls.so.26()(64bit) is needed by contextBroker-1.7.0-1.x86_64
        libgnutls.so.26(GNUTLS_1_4)(64bit) is needed by contextBroker-1.7.0-1.x86_64
```
		
It would be great if you can fix this, because this would allow more people to use your software.
Cheers

**Comment by fgalan** [comment] 2018-03-09 11:24
Which CentOS/RHEL version are you using in the system where you want to install Orion?

**Comment by fgalan** [comment] 2018-03-09 19:19
The RPM you are attempting to install is for CentOS/RHEL 6.x, so I'm afraid is not going to work in your case.

Hoever, there is an ongoing task to set up a CentOS/RHEL 7 respository that I understand is almost completed (this is related with the contents in PR https://github.com/telefonicaid/fiware-orion/pull/3117). @ddmitrii could provide more information if needed.

I recommend to hold on this issue for a while, as the new repo for CentOS/RHEL 7 gets ready.

**Comment by mchoeti** [comment] 2018-03-11 20:01
HI, ok i will do that, now it is time for skiing. I am only pointing that out, because in the docs the yum installation is the [recommended way](http://fiware-orion.readthedocs.io/en/latest/admin/install/index.html#using-yum-recommended). 

> Operating system: CentOS/RedHat. The reference operating system is CentOS 7.4.1708 but it should work also in any later CentOS/RedHat 7.x version.

In the meanwhile i will give docker a try. 
Cheers mc

**Comment by fgalan** [comment] 2018-03-13 08:05
PR #3117 has finally landed. Please have a look to https://fiware-orion.readthedocs.io/en/master/admin/yum/index.html and if that solves your problem, close this issue.

**Comment by preetha2711** [comment] 2018-05-22 07:27
I can't install Orion at all since I am using Homebrew instead of yum and it does not recognise the package name for the context broker.

**Comment by kzangeli** [comment] 2018-05-22 07:44
Homebrew ... that sounds like Mac to me ...
The broker doesn't work on Mac.

**Comment by preetha2711** [comment] 2018-05-22 08:58
Why though, that seems strange to me. I am new to the Fiware platform, might not know the ropes yet.

**Comment by fgalan** [comment] 2018-05-22 09:06
Development resources are limited so from the very begining they have been focused in one OS (which happens to be GNU/Linux) and, within that OS, CentOS/RHEL 7 distribution (although Orion works in other distros, e.g. personally I use it with Debian).

Of course, we would be more than happy to extend Orion to any other operating system. It is written in C++, so it should be (I guess) relatively portable. Thus, contributions on that line (I understand that with some modifications in CMakeList.txt at least) are welcomed!

**Comment by caa06d9c** [comment] 2018-05-22 14:35
@preetha2711, as i mention in message from Fiware Jira (i hope you received it), you should try the docker version, please look here: https://hub.docker.com/r/fiware/orion/

**Comment by fgalan** [comment] 2018-09-27 15:06
After @caa06d9c outstating work, I understand all the RPM-based installation stuff is solved. Have a look to document:

* https://fiware-orion.readthedocs.io/en/master/admin/install/index.html
* https://fiware-orion.readthedocs.io/en/master/admin/yum/index.html

Thus, I'm closing the issue. If I'm wrong, don't hesistate to re-open again and post a comment explaining what the current situation and the problem is. Thanks!

**Closed by fgalan** 2018-09-27 15:06 UTC
Labels: question
