### ISSUE TITLE
Update attribute value to null fails (it doesn't actually change the attribute value)

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2587] opened 2016-10-07 12:59 UTC
Updating an attribute with a `null` value doesn't work:

```
payload='{
  "type": "T",
  "value": null
}'
orionCurl --url /v2/entities/E1/attrs/A1 --payload "$payload" -X PUT
```

The attribute type is changed, but the value stays the same.
The `null` value of A1 in the update is interpreted by the broker as "I don't want to change the value of the attribute".

We may need here a 'bool valueGiven' or something similar to fix this problem.

**Comment by fgalan** [comment] 2016-11-08 16:40
I've tried with current master (1.5.0-next, git version: f75b0e2acf2f62e132ae274608261ca9881b1819) and it seems to work ok.

This is the .test that I have used:

```
# Copyright 2016 Telefonica Investigacion y Desarrollo, S.A.U
#
# This file is part of Orion Context Broker.
#
# Orion Context Broker is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Orion Context Broker is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Orion Context Broker. If not, see http://www.gnu.org/licenses/.
#
# For those usages not covered by this license please contact with
# iot_support at tid dot es

# VALGRIND_READY - to mark the test ready for valgrindTestSuite.sh

--NAME--
Update attr to null bugfix

--SHELL-INIT--
dbInit CB
brokerStart CB

--SHELL--

#
# 01. Create entity with attr value X and type T1
# 02. Get entity and see attr value X and type T1
# 03. Update entity with attr value null and type T2
# 04. Get entity and see attr value null and type T2
#

echo "01. Create entity with attr value X and type T1"
echo "==============================================="
payload='{
  "id": "E",
  "type": "T",
  "A": {
      "value": "X",
      "type": "T1"
   }
}'
orionCurl --url /v2/entities --payload "$payload"
echo
echo


echo "02. Get entity and see attr value X and type T1"
echo "==============================================="
orionCurl --url /v2/entities/E
echo
echo


echo "03. Update entity with attr value null and type T2"
echo "=================================================="
payload='{
  "type": "T2",
  "value": null
}'
orionCurl --url /v2/entities/E/attrs/A --payload "$payload" -X PUT
echo
echo


echo "04. Get entity and see attr value null and type T2"
echo "=================================================="
orionCurl --url /v2/entities/E
echo
echo


--REGEXPECT--
01. Create entity with attr value X and type T1
===============================================
HTTP/1.1 201 Created
Content-Length: 0
Location: /v2/entities/E?type=T
Fiware-Correlator: REGEX([0-9a-f\-]{36})
Date: REGEX(.*)



02. Get entity and see attr value X and type T1
===============================================
HTTP/1.1 200 OK
Content-Length: 65
Content-Type: application/json
Fiware-Correlator: REGEX([0-9a-f\-]{36})
Date: REGEX(.*)

{
    "A": {
        "metadata": {},
        "type": "T1",
        "value": "X"
    },
    "id": "E",
    "type": "T"
}


03. Update entity with attr value null and type T2
==================================================
HTTP/1.1 204 No Content
Content-Length: 0
Fiware-Correlator: REGEX([0-9a-f\-]{36})
Date: REGEX(.*)



04. Get entity and see attr value null and type T2
==================================================
HTTP/1.1 200 OK
Content-Length: 66
Content-Type: application/json
Fiware-Correlator: REGEX([0-9a-f\-]{36})
Date: REGEX(.*)

{
    "A": {
        "metadata": {},
        "type": "T2",
        "value": null
    },
    "id": "E",
    "type": "T"
}


--TEARDOWN--
brokerStop CB
dbDrop CB
```

Maybe I'm doing something different? Pay special attention to step 3.

**Comment by fgalan** [comment] 2016-11-10 21:37
Trying to reproduce, without sucess. Thus, the bug was incorrecntly detected or solved in some way since it was detected and now. A .test covering the case has been added in PR #2655.

Milestone has been assigned to 1.6 (the development cycle in which we have analyzed this and create the .test) although it could have been solved in a previous version.

**Comment by fgalan** [comment] 2017-11-10 16:16
It could be related with #2998 . We reopen it an co-locate in the same milestone by the moment.

**Comment by kzangeli** [comment] 2017-11-11 21:36
New data on this: the functest "null_not_working_in_q_for_subscription.test" fails with the current construct, also, q_and_mq_as_uri_param_for_metadata.test is weird,
Both problems are fixed by removing the 'if' (see updateAttrInNotifyCer in MongoCommonUpdate.cpp).

The cause of the problem is that we don't distinguish between 'not present' and 'null' and this should be addressed

**Comment by kzangeli** [comment] 2017-11-11 21:47
A thought ...
`valueType` for attribute/metadata values is *always* implicit, cannot be given.
What we have 'brainstormed' so far doesn't make any sense (we've been thinking about 'type', not valueType) ...
The 'if clause' in updateAttrInNotifyCer() in MongoCommonUpdate.cpp must be looked over, that is clear.

**Comment by kzangeli** [comment] 2017-11-12 20:34
This should be tested with PATCH as well, if it works as expected with PUT

**Comment by fgalan** [comment] 2017-11-16 14:36
> This should be tested with PATCH as well, if it works as expected with PUT

The .test existing on `cases/2587_attr_update_to_null` covers also the PATCH case. In particular:

```
# 01.  Create entity with six attrs value X and type T1
# 02 . Get entity and see six attrs value X and type T1
# 03a. Update attr A with value null and type T2 using PATCH on entity
# 03b. Update attr B with value null and type T2 using POST on entity
# 03c. Update attr C with value null and type T2 using PUT on attr
# 03d. Update attr D with value null and type T2 using batch update UPDATE
# 03e. Update attr E with value null and type T2 using batch update APPEND
# 03f. Update attr F with attr value null directly
# 04.  Get entity and see five attrs value null and type T2 and one with value null and type T1
```

**Comment by fgalan** [comment] 2017-11-16 14:58
I'm afraid that (again) I'm unable to reproduce this...

I have added a new 2587_attr_update_to_null/attr_update_to_no_value.test in PR https://github.com/telefonicaid/fiware-orion/pull/3042, which is a copy of pre-existing cases/2587_attr_update_to_null.test but wihtout using `value` field instead of `"value": null`.

**Comment by fgalan** [comment] 2017-11-17 08:32
Unable to reproduce. The two .tesf files in cases/2587_attr_update_to_null/ ensure this is work, to the bes of our knowledgue.

**Closed by fgalan** 2017-11-17 08:32 UTC
Labels: APIv2, bug, P6
