### ISSUE TITLE
Unable to connect to MongoDB Replicaset [with SSL]

### ISSUE THREAD

**Issue by Glagnar** [telefonicaid/fiware-orion#3524] opened 2019-07-12 21:15 UTC
I have a MongoDB 3.6 cluster that I am able to connect to in a variety of different ways:

```bash
mongo "mongodb+srv://mongo36lowsec-bneyh.mongodb.net/test" --username user --password mysecret
```
or 
```bash
mongo "mongodb://user:stillsecret@mongo36lowsec-shard-00-00-bneyh.mongodb.net:27017,mongo36lowsec-shard-00-01-bneyh.mongodb.net:27017,mongo36lowsec-shard-00-02-bneyh.mongodb.net:27017/test?ssl=true&replicaSet=mongo36lowsec-shard-0&authSource=admin&retryWrites=true&w=majority"
```
or
```bash
mongo "mongodb://mongo36lowsec-shard-00-00-bneyh.mongodb.net:27017,mongo36lowsec-shard-00-01-bneyh.mongodb.net:27017,mongo36lowsec-shard-00-02-bneyh.mongodb.net:27017/test?replicaSet=mongo36lowsec-shard-0" --ssl --authenticationDatabase admin --username user --password alwaysasecret
```

But how no matter how I start the context broker it fails. This is the millionth try that does not work.... The documentation on this area is pretty sketch from you guy's. Please write just couple more lines about how to connect to a mongodb replica set.
```bash
 -fg -logLevel DEBUG -rplSet mongo36lowsec-shard-0 -dbhost mongo36lowsec-shard-00-00-bneyh.mongodb.net:27017,mongo36lowsec-shard-00-01-bneyh.mongodb.net:27017,mongo36lowsec-shard-00-02-bneyh.mongodb.net:27017 -dbuser user -dbpwd verysecret -t 0-255 -dbTimeout 10000
```

**Comment by fgalan** [comment] 2019-07-17 14:45
Is Orion showing any log traces? They could be useful to debug this.

**Comment by Glagnar** [comment] 2019-07-18 10:24
I am not seeing anything outputted to the logs.
But could you perhaps clarify exactly what the correct way of connecting to a replicates is, the documentation is a but lacking in details. I really just want to make sure we do it the correct way. You can see the three working connection strings I have, but perhaps you will translate that into the command line parameters I need for the context broker.

**Comment by fgalan** [comment] 2019-07-18 10:30
I think the way you are using is the correct one. The only difference compared with similar deployments that I know is the usage of `-dbuser user -dbpwd verysecret` (I don't use it, as in our environment the CB-MongoDB is secured at network layer).

Could you test without those parameters (i.e. setting replica set without authentication), please? Just to know if it works in that case and the problem is in the combination replica set + auth.

**Comment by Glagnar** [comment] 2019-08-13 11:26
Dear @fgalan I have been able to debug further and I suspect it is because the hosted MongoDB servers require SSL.
The MongoDB driver accepts an option to force SSLMode to kSSLEnabled:
http://mongocxx.org/legacy-v1/configuration/#options-setsslmode-and-options-sslmode
When I compile the ContextBroker with the option set, I seem to be able to to connect to the MongoDB.
```c++
mongo::Status status = mongo::client::initialize(Options().setSSLMode(Options::kSSLRequired));
```
But it is not the full answer, I expect more work will be needed to test this - by people who know more about it.

**Comment by fgalan** [comment] 2019-08-14 11:28
>  When I compile the ContextBroker with the option set, I seem to be able to to connect to the MongoDB.

Thanks for the information!

Maybe you could create a pull request to show the exact changes changes you needed to do in the Orion code to make it work to? We have travis CI activated in pull request, so it is a good way of checking if the change if fine with the regression test (it which case it can be merged) or to provide feedback in negative case.

**Comment by Glagnar** [comment] 2019-08-16 07:29
@fgalan I wish I could, but it does not really make sense. While my change enables the ContextBroker to actually connect to the MongoDB, it does not solve all problems. I do not know  the legacy mongodb drivers, MongoDB or even the context broker well enough to make a solution that fully works.

**Comment by fgalan** [comment] 2019-08-16 08:28
Even in that case see how you have solved your case will be helpful to the ones which know context broker and legacy driver good enough to develop a full-fledged solution. Thus, I think it would be a good idea to create that PR.

You say "it does not solve all problems". To which problems do you refer? Could you elaborate a bit, please? Thanks!

**Comment by Glagnar** [comment] 2019-08-21 11:05
Dear @fgalan I have made two screen recordings that might help you debug what is wrong. The first one is using the standard docker image of the fiware context broker:
https://asciinema.org/a/lLxdAjl5Jxv276RBCkdtTlnv0 
It seems that the orion context broker is completely unable to connect to the mongodb.
Here is the git diff where you can see a change that I made to the context broker:
```code
diff --git a/src/lib/mongoBackend/MongoGlobal.cpp b/src/lib/mongoBackend/MongoGlobal.cpp
index c58d16cd9..308560bac 100644
--- a/src/lib/mongoBackend/MongoGlobal.cpp
+++ b/src/lib/mongoBackend/MongoGlobal.cpp
@@ -72,6 +72,7 @@
 *
 * USING
 */
+using mongo::client::Options;
 using mongo::DBClientBase;
 using mongo::DBClientCursor;
 using mongo::BSONObj;
@@ -310,7 +311,7 @@ bool mongoStart

   multitenant = _multitenant;

-  mongo::Status status = mongo::client::initialize();
+  mongo::Status status = mongo::client::initialize(Options().setSSLMode(Options::kSSLRequired));
   if (!status.isOK())
   {
     LM_E(("Database Startup Error %s (cannot initialize mongo client)", status.toString().c_str()));
```
After that update, I am actually able to connect to the database, but I get the errors that you can see in this video:
https://asciinema.org/a/rzUSo4RTercaumIrDOZe9WsqK

**Comment by fgalan** [comment] 2019-08-23 16:25
I have created a PR based in your feedback: https://github.com/telefonicaid/fiware-orion/pull/3542. Let's see how it goes in the test regression done by travis.

With regards to 

> After that update, I am actually able to connect to the database, but I get the errors that you can see in this video

Maybe I have missed some trace but it seems the only one with error is the FATAL one at the end (the other are INFO and DEBUG):

```
time=Wednesday 21 Aug 11:01:16 2019.039Z | lvl=FATAL | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[1645]:restStart | msg=Fatal Error (V4 inet_pton fail for icity-shard-00-02-dkxcq.mongodb.net)
```
Is my interpretation correct?

**Comment by Glagnar** [comment] 2019-08-27 11:42
That is what I saw. 
You are welcome to use the cloud database with the credentials that you see in the video. I will leave it running for a week more. ( Or you can create your own on the MongoDB cloud website, remark though that you must select a dedicated instance for it to work with MongoDB3.6 )

```bash
mongo "mongodb://synchronicity-shard-00-00-dkxcq.mongodb.net:27017,synchronicity-shard-00-01-dkxcq.mongodb.net:27017,synchronicity-shard-00-02-dkxcq.mongodb.net:27017/test?replicaSet=synchronicity-shard-0" --ssl --authenticationDatabase admin --username orion --password orionorion
```
The command above works

**Comment by fgalan** [comment] 2019-08-27 20:19
I'll try. Thanks for setting up the server for the tests!

Which authentication mechanism is using the orion user? SCRAM-SHA-1 or other?

**Comment by fgalan** [comment] 2019-08-29 16:39
Probably the problem you have (the one about `(V4 inet_pton fail for icity-shard-00-02-dkxcq.mongodb.net)`) gets solved in a recent PR https://github.com/telefonicaid/fiware-orion/pull/3544 (already merged).

Thus, could you apply your change to the current code in master branch and test again? I'm still debugging and maybe it stills not working yet, but the result of the test with the new version of the code would be very helpful.

Thanks!

**Comment by fgalan** [comment] 2019-08-30 07:44
I think I finally solved this issue in PR #3544. If you get the code in that PR (30aff89) then you could connect to the replica set you provided:

```
contextBroker -fg -dbhost synchronicity-shard-00-00-dkxcq.mongodb.net:27017,synchronicity-shard-00-01-dkxcq.mongodb.net:27017,synchronicity-shard-00-02-dkxcq.mongodb.net:27017 -rplSet synchronicity-shard-0 -dbuser orion -dbpwd orionorion -dbAuthDb admin -dbSSL -logLevel INFO
...
time=Friday 30 Aug 07:43:42 2019.118Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[1060]:main | msg=Startup completed
```

Note the new CLI switches: `-dbAuthdb` and `-dbSSL`.

@Glagnar could you test and confirm it's working, please?

**Comment by Glagnar** [comment] 2019-09-02 21:23
@fgalan It seems to work. I cloned your branch, compiled, and everything looks good.

**Comment by fgalan** [comment] 2019-09-03 07:00
Thanks! I'll leave opened PR #3452, in the case you want to provide feedback there and/or explicit LGTM.

I think this issue is now solved and can be closed, isn't it?

**Comment by fgalan** [comment] 2019-09-05 06:56
PR was finally merged (in the case of any feedback, we can take it into account and a new PR could be created based on it, of course). Closing issue.

**Closed by fgalan** 2019-09-05 06:56 UTC
