### ISSUE TITLE
Orion cant connect to mongo by DNS

### ISSUE THREAD

**Issue by felixPG** [telefonicaid/fiware-orion#2967] opened 2017-08-23 07:21 UTC
Hi:

Im use the guide published in docker official repository in order to run a contextBroker container, Im use https://hub.docker.com/r/fiware/orion/ STEP 2C.

I have mongo running in other host instead of localhost, so I use **docker run -d --rm --name orion -p 1026:1026 fiware/orion -dbhost 192.168.133.4** .This command work fine and the contextBroker work as expected as you can see bellow.

------------
root@s-smartc2-zprei:/opt/kubernetes/orion# docker run -d --rm --name orion -p 1026:1026 fiware/orion -dbhost 192.168.133.4 -logLevel DEBUG
fa6a530800bb2b5b74543490dad0884e027ef629b52a5243b7e39b3f55639c78
root@s-smartc2-zprei:/opt/kubernetes/orion# curl localhost:1026/version
{
"orion" : {
  "version" : "1.7.0-next",
  "uptime" : "0 d, 0 h, 0 m, 10 s",
  "git_hash" : "bd9f08cf86a631efe6dc1b078ac4c54648860aae",
  "compile_time" : "Fri Jul 21 09:00:32 UTC 2017",
  "compiled_by" : "root",
  "compiled_in" : "b99744612d0b"
}
}
root@s-smartc2-zprei:/opt/kubernetes/orion#

--------------------

So I stop the container and launch a new container but this time using DNS name for mongo database instead of IP.  The command that I use is  **docker run -d --rm --name orion -p 1026:1026 fiware/orion -dbhost mongo-0.mongo** and the result is NOT as expected, contextBroker is unable to connect to my mongo, that is the same mongo in the command before (using IP) but with the DNS name.

-----------------------

root@s-smartc2-zprei:/opt/kubernetes/orion# docker run --rm -d --name orion1 -p 1026:1026 fiware/orion -dbhost mongo-0.mongo -logLevel DEBUG
3544909a7a64cb217ae80e04fcd0426ba642dadcff3dd923da7f77d35775bb55
root@s-smartc2-zprei:/opt/kubernetes/orion#
root@s-smartc2-zprei:/opt/kubernetes/orion#
root@s-smartc2-zprei:/opt/kubernetes/orion# curl localhost:1026/version
curl: (56) Recv failure: Conexión reinicializada por la máquina remota

**PIng from the container to mongo-0.mongo**

[root@6dcc841ffc4e /]# ping mongo-0.mongo
PING mongo-0.mongo (192.168.133.4) 56(84) bytes of data.
64 bytes from mongo-0.mongo (192.168.133.4): icmp_seq=1 ttl=63 time=0.323 ms
64 bytes from mongo-0.mongo (192.168.133.4): icmp_seq=2 ttl=63 time=0.384 ms
64 bytes from mongo-0.mongo (192.168.133.4): icmp_seq=3 ttl=63 time=0.378 ms
64 bytes from mongo-0.mongo (192.168.133.4): icmp_seq=4 ttl=63 time=0.308 ms
64 bytes from mongo-0.mongo (192.168.133.4): icmp_seq=5 ttl=63 time=0.312 ms
^C
--- mongo-0.mongo ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4416ms
rtt min/avg/max/mdev = 0.308/0.341/0.384/0.033 ms
[root@6dcc841ffc4e /]#

-------------------------------------------

[root@6dcc841ffc4e /]# cat /var/log/contextBroker/contextBroker.log
time=2017-08-23T07:18:34.257Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[1707]:main | msg=Orion Context Broker is running
time=2017-08-23T07:18:34.261Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[152]:mongoConnect | msg=**Database Startup Error (cannot connect to mongo** - doing 100 retries with a 1000 microsecond interval)

----------------------------------------------------------

Could you help me with this please?

**Comment by felixPG** [comment] 2017-08-23 09:28
Only for confirmation, I make other test, install orion from fiware repo using yum, put in the config file (/etc/sysconfig/contextBroker) the mongo-0.mongo as the dabatase, and is working OK. So, what is the problem using the container from your docker official repo?

**Comment by fgalan** [comment] 2017-08-23 13:16
Let's compare the following:

* Result of `ps ax | grep contextBroker` in your the test done in your host, after installing Orion as RPM using yum.
* Result of `ps ax | grep contextBroker` inside the docker container when the problem happens.

The purpose is to compare the CLI used in both cases. Please, provide that feedback in a comment in this issue.

**Comment by felixPG** [comment] 2017-08-24 06:59
Hi:

I dont know what happend that all is working now, here the result:

FROM Docker with IP address

[root@ca9746b6392a /]# ps ax | grep contextBroker
    1 ?        Ssl    0:00 /usr/bin/contextBroker -fg -multiservice -dbhost 192.168.133.4 -logLevel DEBUG
   32 ?        S+     0:00 grep contextBroker
[root@ca9746b6392a /]# curl localhost:1026/version
{
"orion" : {
  "version" : "1.7.0-next",
  "uptime" : "0 d, 0 h, 1 m, 26 s",
  "git_hash" : "bd9f08cf86a631efe6dc1b078ac4c54648860aae",
  "compile_time" : "Fri Jul 21 09:00:32 UTC 2017",
  "compiled_by" : "root",
  "compiled_in" : "b99744612d0b"
}
}
[root@ca9746b6392a /]#

FROM Docker with DNS name

[root@5a8500a943b4 /]# ps aux | grep contextBroker
root         1  0.0  0.6 224176 13768 ?        Ssl  06:52   0:00 /usr/bin/contextBroker -fg -multiservice -dbhost mongo-0.mongo -logLevel DEBUG -logDir /var/log/contextBroker
root       151  0.0  0.0   6436   616 ?        S+   06:54   0:00 grep contextBroker
[root@5a8500a943b4 /]# curl localhost:1026/version
{
"orion" : {
  "version" : "1.7.0-next",
  "uptime" : "0 d, 0 h, 1 m, 57 s",
  "git_hash" : "bd9f08cf86a631efe6dc1b078ac4c54648860aae",
  "compile_time" : "Fri Jul 21 09:00:32 UTC 2017",
  "compiled_by" : "root",
  "compiled_in" : "b99744612d0b"
}
}
[root@5a8500a943b4 /]#

FROM Host with DNS name

![fromhost](https://user-images.githubusercontent.com/30522864/29653490-4f54a892-88aa-11e7-8125-39aced06fdbf.png)

Same test than yesterday but now is working, Strange!!!!
Thank you for your reply

**Comment by fgalan** [comment] 2017-08-24 08:15
Happy to know finally solved it!

Maybe it was due to some kind of temporral glitch related with DNS resolution or the underlaying docker networking. Anyway, it didn't seem to be directly related with Orion.

Given the issue is solved, I'm closing the issue.

**Closed by fgalan** 2017-08-24 08:15 UTC
