### ISSUE TITLE
Error on keep-alive requests

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-orion#1539] opened 2015-11-25 09:44 UTC
Using Orion 0.25, we are getting a systematic and reproducible error :

```
WARNING@09:07:10  xmlRequest.cpp[231]: Bad Input ('<updateContextRequest', 'expected <')
```

This error occurs on the second `updateContext` request when the second request has a smaller size than the first one. This only occurs when using keep-alive connections, so this cannot be reproduced using wget/curl command line tools, but with tools like Postman.

A workaround is to disable keep-alive on client-side.
We suspect a bad reuse of a bigger buffer passed to RapidXML... like forgetting to terminate the string with a NULL character (http://stackoverflow.com/a/23877015/164251).

# First request (length: 767) :

```
POST /v1/updateContext HTTP/1.1
Host: server:1026
Connection: keep-alive
Content-Length: 767
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Fiware-Service: smartcity
Fiware-ServicePath: /lora
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Content-Type: application/xml
Accept: application/xml
Cache-Control: no-cache
Postman-Token: afa9d5db-f66d-ebab-4945-9a7c5d70f0a0
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4

<updateContextRequest><updateAction>APPEND</updateAction><contextElementList><contextElement><entityId type="tracker" isPattern="false"><id>20635F0012000011</id></entityId><contextAttributeList><contextAttribute><name>temperature</name><type>double</type><contextValue>26.91</contextValue><metadata/></contextAttribute><contextAttribute><name>mode</name><type>string</type><contextValue>POSITION</contextValue><metadata/></contextAttribute><contextAttribute><name>position</name><type>coords</type><contextValue>43.6333568, 1.3759744</contextValue><metadata><contextMetadata><name>location</name><type>string</type><value>WGS84</value></contextMetadata></metadata></contextAttribute></contextAttributeList></contextElement></contextElementList></updateContextRequest>
```

```
HTTP/1.1 200 OK
Content-Length: 1202
Content-Type: application/xml
Date: Wed, 25 Nov 2015 09:07:07 GMT

<updateContextResponse>
  <contextResponseList>
    <contextElementResponse>
      <contextElement>
        <entityId type="tracker" isPattern="false">
          <id>20635F0012000011</id>
        </entityId>
        <contextAttributeList>
          <contextAttribute>
            <name>temperature</name>
            <type>double</type>
            <contextValue></contextValue>
          </contextAttribute>
          <contextAttribute>
            <name>mode</name>
            <type>string</type>
            <contextValue></contextValue>
          </contextAttribute>
          <contextAttribute>
            <name>position</name>
            <type>coords</type>
            <contextValue></contextValue>
            <metadata>
              <contextMetadata>
                <name>location</name>
                <type>string</type>
                <value>WGS84</value>
              </contextMetadata>
            </metadata>
          </contextAttribute>
        </contextAttributeList>
      </contextElement>
      <statusCode>
        <code>200</code>
        <reasonPhrase>OK</reasonPhrase>
      </statusCode>
    </contextElementResponse>
  </contextResponseList>
</updateContextResponse>
```

# Second request (length: 524)

```
POST /v1/updateContext HTTP/1.1
Host: server:1026
Connection: keep-alive
Content-Length: 524
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Fiware-Service: smartcity
Fiware-ServicePath: /lora
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Content-Type: application/xml
Accept: application/xml
Cache-Control: no-cache
Postman-Token: 2a690536-0cdf-8341-2f78-59ac9cf714cd
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4

<updateContextRequest><updateAction>APPEND</updateAction><contextElementList><contextElement><entityId type="tracker" isPattern="false"><id>20635F0012000011</id></entityId><contextAttributeList><contextAttribute><name>temperature</name><type>double</type><contextValue>25.5</contextValue><metadata/></contextAttribute><contextAttribute><name>mode</name><type>string</type><contextValue>LORALIVE</contextValue><metadata/></contextAttribute></contextAttributeList></contextElement></contextElementList></updateContextRequest>
```
```
HTTP/1.1 200 OK
Content-Length: 126
Content-Type: application/xml
Date: Wed, 25 Nov 2015 09:07:10 GMT

<orionError>
  <code>400</code>
  <reasonPhrase>Bad Request</reasonPhrase>
  <details>XML Parse Error</details>
</orionError>
```

# Orion log

```
orion_1 | INFO@09:07:07  rest.cpp[952]: Starting transaction from 86.206.94.181:49626/v1/updateContext
orion_1 | INFO@09:07:07  connectionOperations.cpp[74]: Database Operation Successful (query: { _id.id: "20635F0012000011", _id.type: "tracker", _id.servicePath: /^\/lora$/ })
orion_1 | INFO@09:07:07  rest.cpp[475]: Transaction ended
orion_1 | INFO@09:07:10  rest.cpp[952]: Starting transaction from 86.206.94.181:49626/v1/updateContext
orion_1 | WARNING@09:07:10  xmlRequest.cpp[231]: Bad Input ('<updateContextRequest', 'expected <')
orion_1 | INFO@09:07:10  rest.cpp[475]: Transaction ended
```

You can inspect the complete TCP steam using the provided pcap capture : http://s000.tinyupload.com/download.php?file_id=42180466693057179622&t=4218046669305717962252621.

**Comment by fgalan** [comment] 2015-11-26 13:19
This could have the same "root cause" than https://github.com/telefonicaid/fiware-orion/issues/1500.

**Comment by marcc-orange** [comment] 2015-11-26 13:42
Yes it seem like the same bug as #1500. We are using the docker image : fiware/orion:0.25.
This is what `/version/` returns:
```
{
  "orion": {
    "version": "0.25.0-next",
    "uptime": "0 d, 22 h, 37 m, 2 s",
    "git_hash": "e855f89776787652a6ab288e2e7bbc504ee1d545",
    "compile_time": "Mon Nov 2 09:06:47 UTC 2015",
    "compiled_by": "root",
    "compiled_in": "838a42ae8431"
  }
}
```
We'll switch to 0.26 as soon as it's out ! Thanks.

**Comment by fgalan** [comment] 2015-11-26 14:13
I'd suggest to try with the newest develop snapshot. Docker at fiware/orion (without ":0.25") always points to develop HEAD.

**Comment by marcc-orange** [comment] 2015-11-26 15:02
I confirm the bug could not be reproduced with the latest fiware/orion image (b34245aaaf89).

```
<orion>
    <version>0.25.0-next</version>
    <uptime>0 d, 0 h, 2 m, 24 s</uptime>
    <git_hash>97010ed69e5305bd5ceb53c2ac61ee15ec9174b0</git_hash>
    <compile_time>Thu Nov 26 13:31:57 UTC 2015</compile_time>
    <compiled_by>root</compiled_by>
    <compiled_in>838a42ae8431</compiled_in>
</orion>
```
Thanks.

**Comment by fgalan** [comment] 2015-11-26 15:07
Great! In that case, I'd suggest to close this issue.

**Closed** 2015-11-26 15:36 UTC
Labels: bug
