### ISSUE TITLE
Broker fails to close used connections and they remain in CLOSE_WAIT

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2166] opened 2016-05-20 12:43 UTC
It seems, as discovered by a client, that the broker sometimes leaves used connections without closing them, causing all fds to be used and consequently the broker stops working.

The broker uses _libmicrohttpd (MHD)_ to respond to requests and _libcurl_ for notifications and forwarding of messages and it seems libcurl might be responsible for the detected problem.

**Comment by kzangeli** [comment] 2016-05-20 12:44
Similar problem described in SOF:
http://stackoverflow.com/questions/12730477/close-is-not-closing-socket-properly

**Comment by fgalan** [comment] 2016-05-23 19:37
I understand that the problem has been discoverd in Orion 0.26.1. Reviewing the changelog from Orion 0.26.1 to Orion 1.1 (the current one) note the following in [Orion 0.28.0 release notes](https://github.com/telefonicaid/fiware-orion/releases/tag/0.28.0):

> Fix: libmicrohttpd 0.9.48 included in contextBroker as static lib (previous Orion versions used 0.9.22 as dynamic library) (Issue #1675)

If the problem cause points to libmicrohttpd, it should be reviewed if 0.9.48 has solved it.

**Comment by crbrox** [comment] 2016-05-27 07:37
Finally, it seems an expected behavior if the limit of file descriptors for the process is not high enough. With notification mode set as `threadpool` , each thread can hold up to 5 connections (libcurl pool). So, for outgoing request, 5*(number of pool's threads) file descriptors are needed to avoid exhausting the available fds

The total limit of  fds should include the number of simultaneous incoming request in MHD, plus an amount for logs, listening sockets and file descriptors used by libraries
`maxCon + 5 * no of threads + X` 

Or the number of threads in the pool can be lowered consequently

**Comment by fgalan** [comment] 2016-05-27 10:00
After analyzing this, it seem it isn't a problem in the code, but something that need to be documented. Thus, removing "bug" label and adding "doc" label.

**Comment by fgalan** [comment] 2016-05-30 15:25
Doc modifications in PR #2214

**Comment by mrutid** [comment] 2016-11-26 10:49
It's happening...

**Comment by fgalan** [comment] 2016-11-28 19:27
Recovering this issue for the 1.7.0 milestone.

**Comment by fgalan** [comment] 2016-12-05 11:12
After researching on this, CLOSE_WAIT are not the root of the problem: the root of the problem is fd exahustion when select() was used in MHD (which is the scope of issue #2724).

However, documentation should be improved to explain this better so this issue will remain opened.

**Comment by fgalan** [comment] 2016-12-07 11:55
Documentation completed in PR https://github.com/telefonicaid/fiware-orion/pull/2755. Closing.

**Closed by fgalan** 2016-12-07 11:55 UTC
Labels: bug, P8
