### ISSUE TITLE
Unexpected response:   "invalid context provider response "

### ISSUE THREAD

**Issue by sergg75** [telefonicaid/fiware-orion#1608] opened 2015-12-09 14:47 UTC
When  sending a queryContext to orion.lab.fiware (v.026), e.g.:

{"entities":[{"type":"bikerenting","isPattern":"true","id":"Sevici.206"}]} 

when the entity is registered in a context provider, orion forwards the query to the provider. The response from the provider to orion.lab is:

 <code>
&lt;queryContextResponse&gt;&lt;contextResponseList&gt;&lt;contextElementResponse&gt;&lt;contextElement&gt;&lt;entityId isPattern="false" type="bikerenting"&gt;&lt;id&gt;Sevici.206&lt;/id&gt;&lt;/entityId&gt;&lt;contextAttributeList&gt;&lt;contextAttribute&gt;&lt;name&gt;available&lt;/name&gt;&lt;type&gt;integer&lt;/type&gt;&lt;contextValue&gt;0&lt;/contextValue&gt;&lt;/contextAttribute&gt;&lt;contextAttribute&gt;&lt;name&gt;free&lt;/name&gt;&lt;type&gt;integer&lt;/type&gt;&lt;contextValue&gt;15&lt;/contextValue&gt;&lt;/contextAttribute&gt;&lt;contextAttribute&gt;&lt;name&gt;total&lt;/name&gt;&lt;type&gt;integer&lt;/type&gt;&lt;contextValue&gt;15&lt;/contextValue&gt;&lt;/contextAttribute&gt;&lt;contextAttribute&gt;&lt;name&gt;ticket&lt;/name&gt;&lt;type&gt;integer&lt;/type&gt;&lt;contextValue&gt;1&lt;/contextValue&gt;&lt;/contextAttribute&gt;&lt;contextAttribute&gt;&lt;name&gt;open&lt;/name&gt;&lt;type&gt;integer&lt;/type&gt;&lt;contextValue&gt;1&lt;/contextValue&gt;&lt;/contextAttribute&gt;&lt;contextAttribute&gt;&lt;name&gt;timeinstant&lt;/name&gt;&lt;type&gt;urn:x-ogc:def:trs:IDAS:1.0:ISO8601&lt;/type&gt;&lt;contextValue&gt;2015-12-09T15:15:14.000000Z&lt;/contextValue&gt;&lt;/contextAttribute&gt;&lt;contextAttribute&gt;&lt;name&gt;connected&lt;/name&gt;&lt;type&gt;integer&lt;/type&gt;&lt;contextValue&gt;1&lt;/contextValue&gt;&lt;/contextAttribute&gt;&lt;contextAttribute&gt;&lt;name&gt;position&lt;/name&gt;&lt;type&gt;coords&lt;/type&gt;&lt;contextValue&gt;37.40296354842764,-5.958211097806437&lt;/contextValue&gt;&lt;metadata&gt;&lt;contextMetadata&gt;&lt;name&gt;location&lt;/name&gt;&lt;type&gt;string&lt;/type&gt;&lt;value&gt;WGS84&lt;/value&gt;&lt;/contextMetadata&gt;&lt;/metadata&gt;&lt;/contextAttribute&gt;&lt;contextAttribute&gt;&lt;name&gt;street&lt;/name&gt;&lt;type&gt;string&lt;/type&gt;&lt;contextValue&gt;Avenida Kansas City  Aprox. C Macedonia  &lt;/contextValue&gt;&lt;/contextAttribute&gt;&lt;/contextAttributeList&gt;&lt;/contextElement&gt;&lt;statusCode&gt;&lt;code&gt;200&lt;/code&gt;&lt;reasonPhrase&gt;OK&lt;/reasonPhrase&gt;&lt;/statusCode&gt;&lt;/contextElementResponse&gt;&lt;/contextResponseList&gt;&lt;/queryContextResponse&gt;
</code> 

It looks correct (nothing has changed here for months) but the response from orion.lab is.

<code>
&lt;queryContextResponse&gt;
  &lt;errorCode&gt;
    &lt;code&gt;404&lt;/code&gt;
    &lt;reasonPhrase&gt;No context element found&lt;/reasonPhrase&gt;
    &lt;details&gt;invalid context provider response&lt;/details&gt;
  &lt;/errorCode&gt;
&lt;/queryContextResponse&gt;
</code>

**Comment by sergg75** [comment] 2015-12-09 17:00
This functionality has worked properly for months. It stopped working between the 3rd and the 8th of December, probably because the entities registration expired on the 5th. They were registered again on the 9th, but it never worked again.

**Comment by kzangeli** [comment] 2015-12-09 17:14
When you say 'registered again'. I guess you mean a NEW registration, having the entities registered twice.
Why not try to do a registration-update (using the old registration-id in the request)?

However, it may simply be a bug in the broker, getting confused when finding more than one registration.
Perhaps the first one is considered (being outdated) and the second one (the valid one) is not even taken into consideration ...

Needs to be investigated.

**Comment by fgalan** [comment] 2015-12-09 18:45
> They were registered again

It would be great if you could add the re-registration message as comment to this issue, in order to ease reproducing the issue.

**Comment by sergg75** [comment] 2015-12-09 18:49
Yes, it's a new registration, because the old one expired. Both for the same provider. 
However, the context broker forwards the requests properly to the provider (once).
There are multiple registrations that apply here. The one for he example is:

2015-06-05 14:49:26.655184 http://orion.lab.fiware.org:1026
 {'type': 'bikerenting', 'id': 'Sevici.104', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Sevici.105', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Sevici.106', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Sevici.107', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Sevici.108', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Sevici.109', 'isPattern': 'false'}, 
ETC
{'type': 'bikerenting', 'id': 'Sevici.206', 'isPattern': 'false'}, 
ETC
 'attributes': [{'isDomain': 'false', 'type': 'integer', 'name': 'available'}, {'isDomain': 'false', 'type': 'integer', 'name': 'free'}, {'isDomain': 'false', 'type': 'integer', 'name': 'total'}, {'isDomain': 'false', 'type': 'integer', 'name': 'ticket'}, {'isDomain': 'false', 'type': 'integer', 'name': 'open'}, {'isDomain': 'false', 'type': 'urn:x-ogc:def:trs:IDAS:1.0:ISO8601', 'name': 'timeinstant'}, {'isDomain': 'false', 'type': 'integer', 'name': 'connected'}, {'isDomain': 'false', 'type': 'coords', 'name': 'position'}, {'isDomain': 'false', 'type': 'string', 'name': 'street'}]}]}
 {
  "duration" : "P6M",
  "registrationId" : "56680fdf8520c7cc15b4ab93"
}

**Comment by fgalan** [comment] 2015-12-09 18:51
What operation has you use to register? `POST /v1/registerContext`?

**Comment by sergg75** [comment] 2015-12-09 21:46
This is a registration request
url 
http://orion.lab.fiware.org:1026/v1/registry/registerContext
headers 
{'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': 'Wrebo394MCABvjWN2KiYlZB5jdqwJk'}
 payload 
{'duration': 'P6M', 'contextRegistrations': [{'providingApplication': 'http://130.206.85.12:10026/v1', 'entities': [{'type': 'bikerenting', 'id': 'Seivic.2', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.3', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.4', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.5', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.6', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.7', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.8', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.9', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.10', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.11', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.12', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.13', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.14', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.15', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.16', 'isPattern': 'false'}, {'type': 'bikerenting', 'id': 'Seivic.17', 'isPattern': 'false'}], 'attributes': [{'isDomain': 'false', 'type': 'integer', 'name': 'available'}, {'isDomain': 'false', 'type': 'integer', 'name': 'free'}, {'isDomain': 'false', 'type': 'integer', 'name': 'total'}, {'isDomain': 'false', 'type': 'integer', 'name': 'ticket'}, {'isDomain': 'false', 'type': 'integer', 'name': 'open'}, {'isDomain': 'false', 'type': 'urn:x-ogc:def:trs:IDAS:1.0:ISO8601', 'name': 'timeinstant'}, {'isDomain': 'false', 'type': 'integer', 'name': 'connected'}, {'isDomain': 'false', 'type': 'coords', 'name': 'position'}, {'isDomain': 'false', 'type': 'string', 'name': 'street'}]}]}

**Comment by fgalan** [comment] 2015-12-10 10:31
A curl-ized version of the registerContext provided by @sergg75 (without X-Auth-Token):

```
(curl localhost:1026/v1/registry/registerContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
	"duration": "P6M",
	"contextRegistrations": [{
		"providingApplication": "http://130.206.85.12:10026/v1",
		"entities": [{
			"type": "bikerenting",
			"id": "Seivic.2",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.3",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.4",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.5",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.6",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.7",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.8",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.9",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.10",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.11",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.12",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.13",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.14",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.15",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.16",
			"isPattern": "false"
		}, {
			"type": "bikerenting",
			"id": "Seivic.17",
			"isPattern": "false"
		}],
		"attributes": [{
			"isDomain": "false",
			"type": "integer",
			"name": "available"
		}, {
			"isDomain": "false",
			"type": "integer",
			"name": "free"
		}, {
			"isDomain": "false",
			"type": "integer",
			"name": "total"
		}, {
			"isDomain": "false",
			"type": "integer",
			"name": "ticket"
		}, {
			"isDomain": "false",
			"type": "integer",
			"name": "open"
		}, {
			"isDomain": "false",
			"type": "urn:x-ogc:def:trs:IDAS:1.0:ISO8601",
			"name": "timeinstant"
		}, {
			"isDomain": "false",
			"type": "integer",
			"name": "connected"
		}, {
			"isDomain": "false",
			"type": "coords",
			"name": "position"
		}, {
			"isDomain": "false",
			"type": "string",
			"name": "street"
		}]
	}]
}
EOF
```

**Comment by fgalan** [comment] 2015-12-10 12:29
After debugging with @sergg75, this was not actually a bug in CB, but a misconfiguration at the client side. Orion was forwarding in JSON (due to the registration was done in JSON) but the CPr answered in XML.

Thus, closing.

**Closed by fgalan** 2015-12-10 12:29 UTC
Labels: bug
