### ISSUE TITLE
Get all subscriptions not working

### ISSUE THREAD

**Issue by mhinojosa15** [telefonicaid/fiware-orion#4543] opened 2024-05-14 07:02 UTC
**Bug description**

I have many subscriptions from a subservice and when I get all the subscriptions I get a 404 error. I have tried with other subservices and I get the same error. Is it possible that the API is not working properly?

- Orion version: 3.7.0

**How to reproduce it**
Steps to reproduce the behavior (as an example)
1. Get all subscriptions:
    ```BASH
       curl --location 'http://MY_URL:5001/v2/subscriptions' \
        --header 'Fiware-Service: dipbad' \
        --header 'Fiware-ServicePath: /livSmartBeachesChelesDatakorum' \
        --header 'X-Auth-Token: MY_TOKEN' \
        --header 'Cookie: iot-portal=S1' 
    ```
2. See 404 error in this request response
 
![image](https://github.com/telefonicaid/fiware-orion/assets/64640295/66585db1-3683-481e-9af9-98e1c4323724)

How can I solve that error?

**Comment by fgalan** [comment] 2024-05-14 07:47
Orion is unable of generating this kind of body in 404 errors

![imagen](https://github.com/telefonicaid/fiware-orion/assets/1534240/2a615cb7-83db-4903-b848-99b5dc3bcee8)

Thus, I don't think this issue is related with Orion at all. Probably some service in the middle (load balancer, etc.) is creating the problem.

I'm going to close the issue. Please reopen it with new evidences that shows the problem is actually related with Orion. Thanks for the feedback!

**Closed by fgalan** 2024-05-14 07:47 UTC
Labels: bug
