### ISSUE TITLE
No response on Entity creation command.

### ISSUE THREAD

**Issue by saurabhjangir** [telefonicaid/fiware-orion#3102] opened 2018-02-09 10:42 UTC
When we create any entity it doesn't give any message as a response. I think it should be implemented. User should get a message for a successful creation of entity with an HTTP code 201 Created.

```
[root@localhost fiware-orion]# curl localhost:1026/v2/entities -s -S --header 'Content-Type: application/json' -d @- <<EOF
 {
   "id": "Room111",
   "type": "Room",
   "temperature": {
     "value": 23,
     "type": "Float"
   },
   "pressure": {
     "value": 720,
     "type": "Integer"
   }
 }
 EOF
[root@localhost fiware-orion]#
```
This is happened when we create an entity. We should give user a message for successful creation.

**Comment by fgalan** [comment] 2018-02-09 10:48
By default curl doesn't show response codes. Try using `-vvvv` as parameter in the curl and let's see how it goes.

**Comment by saurabhjangir** [comment] 2018-02-09 10:54
Yes we are getting code with -vv option. But in case we don't use -vv, atleast there should be a message other then code. For example, if we create a already created entity we get an error and desciption as output,

>[root@localhost fiware-orion]# curl localhost:1026/v2/entities -s -S --header 'Content-Type: application/json' -d @- <<EOF
> {
>   "id": "Room11111",
>   "type": "Room",
>   "temperature": {
>     "value": 23,
>     "type": "Float"
>   },
>   "pressure": {
>     "value": 720,
>     "type": "Integer"
>   }
> }
> EOF
>**{"error":"Unprocessable","description":"Already Exists"}**

We can add similar type of message with creation command.

**Comment by fgalan** [comment] 2018-02-09 13:08
In the case of error it makes sense to include a description of the error in the JSON payload, so you are getting such payload. However, in the case of successfull entity creation (or, in general, in the case of any successfull operation) the RESET client only needs to know that it went ok with a 2xx HTTP code (in the particular case of entity creation, it is 201 Created, other operations use 204 No Cotent).

Note that the regular consumer of the Orion API is programatic applications. Tools like `curl` are fine to quick testing and debugging but the API is not designed to be verbose for curl users (and, even in that case, you have the `-vvvv` option if you want to have full information).

Of course, all the above is somehow matter of opinion :) but it the design principle that has been choosen for NGSIv2.

Other nice tool that I recommend you as alternative to curl is [Postman](https://www.getpostman.com/), in the case you didn't already know it.

**Comment by juliozinga** [comment] 2018-02-09 13:32
Other tool is https://insomnia.rest. This example, it shows four aba(preview, header, cookie, timeline).
Timeline aba return:

```
* Preparing request to http://localhost:1030/v2/entities
* Using libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.11 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Found bundle for host localhost: 0x3b215dc00ec0 [can pipeline]
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (::1) port 1030 (#0)
> POST /v2/entities HTTP/1.1
> Host: localhost:1030
> User-Agent: insomnia/5.12.4
> Content-Type: application/json
> Accept: application/json
> Fiware-Service: orion
> Fiware-ServicePath: /sof1
> Content-Length: 135
| {
| "id": "Room11111",
| "type": "Room",
| "temperature": {
| "value": 23,
| "type": "Float"
| },
| "pressure": {
| "value": 720,
| "type": "Integer"
| }
| }
* upload completely sent off: 135 out of 135 bytes
< HTTP/1.1 201 Created
< Connection: Keep-Alive
< Content-Length: 0
< Location: /v2/entities/Room11111?type=Room
< Fiware-Correlator: 5895b78e-0d9d-11e8-8da8-0242ac110005
< Date: Fri, 09 Feb 2018 13:30:08 GMT

* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by saurabhjangir** [comment] 2018-02-09 15:59
@fgalan yes I know about postman :) anyways I got the point. Thanks for your response @fgalan & @juliozinga :)

**Comment by juliozinga** [comment] 2018-02-11 01:19
I found this option "-iX" with curl:
`curl -iX GET http://localhost:1030/version`

```
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 361
Content-Type: application/json
Fiware-Correlator: 3c8aaed2-0ec9-11e8-85f7-0242ac110005
Date: Sun, 11 Feb 2018 01:16:50 GMT

{
"orion" : {
  "version" : "1.10.0-next",
  "uptime" : "0 d, 0 h, 3 m, 1 s",
  "git_hash" : "0f92803495a8b6c145547e19f35e8f633dec92e0",
  "compile_time" : "Fri Feb 2 09:45:41 UTC 2018",
  "compiled_by" : "root",
  "compiled_in" : "77ff7f334a88",
  "release_date" : "Fri Feb 2 09:45:41 UTC 2018",
  "doc" : "https://fiware-orion.readthedocs.org/en/master/"
}
}

```

@saurabhjangir  I think you can close this Issue.

**Comment by fgalan** [comment] 2018-02-12 09:56
I understand the issue is closeable. Doing so.

**Closed by fgalan** 2018-02-12 09:56 UTC
Labels: question
