### ISSUE TITLE
Broker to use poll and not select 

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2724] opened 2016-11-25 15:20 UTC
We need to modify the broker (**restInit** in `rest.cpp`) so that MHD uses `poll` and not `select`.
Select only supports 1024 simultaneous connections and some configurations might need more than that.
Also, there is a possibility we gain some performance using poll/epoll instead of select.

A few unfruitful attempts have been made, but select is still used (check done with `strace contextBroker -fg`) and not poll ...

**Comment by fgalan** [comment] 2016-11-28 14:59
We should take into account not only MHD but also libcurl

**Comment by fgalan** [comment] 2016-11-28 19:26
Maybe the usage of `-maxConnection` CLI should be changed after implementing this issue. The following thread provides extra information regarding the MHD_OPTION_CONNECTION_LIMIT parameter in which `-maxConnection` is (currently, let's see in the future with epoll()) based http://lists.gnu.org/archive/html/libmicrohttpd/2016-11/msg00014.html

**Comment by kzangeli** [comment] 2016-11-29 10:37
About libcurl, there seems to be a way to ask libcurl to use poll and not select, however, we will need to rewrite all the curl code, as we right now use 'easy_curl', which only supports select().
We need to use'multi_curl':

https://curl.haxx.se/libcurl/c/libcurl-multi.html

**Comment by mariolg** [comment] 2016-11-29 15:35
MHD_USE_POLL
Use poll() instead of select(). This allows sockets with descriptors >= FD_SETSIZE. This option currently only works in conjunction with MHD_USE_THREAD_PER_CONNECTION or MHD_USE_INTERNAL_SELECT (at this point). If you specify MHD_USE_POLL and the local platform does not support it, MHD_start_daemon will return NULL.

MHD_USE_EPOLL_LINUX_ONLY
Use epoll() instead of poll() or select(). This allows sockets with descriptors >= FD_SETSIZE. This option is only available on Linux systems and does not work in conjunction with MHD_USE_THREAD_PER_CONNECTION (at this point). If you specify MHD_USE_EPOLL_LINUX_ONLY and the local platform does not support it, MHD_start_daemon will return NULL. Using epoll() instead of select() or poll() can in some situations result in significantly higher performance as the system call has fundamentally lower complexity (O(1) for epoll() vs. O(n) for select()/poll() where n is the number of open connections).

Due to the fact that MHD_USE_THREAD_PER_CONNECTION  is not allowed in conjunction with poll/epoll then the CLI option -reqPoolSize. _Size of thread pool for incoming connections. Default value is 0, meaning no thread pool_ => will not have sense, I guess.

**Comment by fgalan** [comment] 2016-11-29 18:47
Relevant thread at libmicrohttpd mailing list: http://lists.gnu.org/archive/html/libmicrohttpd/2016-11/msg00020.html

**Comment by fgalan** [comment] 2016-11-30 17:01
> About libcurl, there seems to be a way to ask libcurl to use poll and not select, however, we will need to rewrite all the curl code, as we right now use 'easy_curl', which only supports select().
We need to use'multi_curl':
>
> https://curl.haxx.se/libcurl/c/libcurl-multi.html

Recent research on the topic shown that libcurl (in the way we use at CB) doesn't use select internally, as we have reproduce a case with 4000 outgoing notification connections (and 4000 is greater than 1024, the limit with select).

Thus, the only limit seems to be at MHD.

**Comment by fgalan** [comment] 2016-12-05 11:10
Implementation done at PR https://github.com/telefonicaid/fiware-orion/pull/2751. However, documentation at perf_tuning.md should be improved based in what we have learnt and implemented, so this issue will remain open yet a little bit.

**Comment by fgalan** [comment] 2016-12-07 11:54
Documentation completed in PR https://github.com/telefonicaid/fiware-orion/pull/2755

**Comment by fgalan** [comment] 2016-12-07 11:54
Assigning to @iariasleon for QA validation.

**Comment by fgalan** [comment] 2016-12-09 09:33
Doc still pending on this http://lists.gnu.org/archive/html/libmicrohttpd/2016-12/msg00022.html

**Comment by iariasleon** [comment] 2016-12-12 10:52
Bug detected:
If try to start by service (`service contextBroker start`) and the config used is `-notificationMode threadpool:60000:1022` (1022 or higher), the CB does not start, showing in log this line:
```
time=2016-12-12T10:13:08.340Z | lvl=FATAL | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[1547]:restStart | msg=Fatal Error (error starting REST interface)
```
If the CB is started by command (`/usr/bin/contextBroker ....`) it is started successfully.

**Comment by fgalan** [comment] 2016-12-12 11:16
My bet: the thread limit is not being honoured when CB runs as a service. If I'm right, then a procedure to set thread limit for processes running for processes would solve this problem.

**Comment by iariasleon** [comment] 2016-12-13 12:04
Coment related to https://github.com/telefonicaid/fiware-orion/issues/2724#issuecomment-266398438

The contextBroker should be started by command (`/usr/bin/contextBtoker ...`) instead of service (service contextBroker start), because the VMs are limited the number of threads (1024) in all users except in `root`.

**Comment by iariasleon** [comment] 2016-12-13 12:05
LGTM

See report in DM-2377

**Closed by iariasleon** 2016-12-13 12:05 UTC
Labels: must, techdebt
