### ISSUE TITLE
Possible bug  processing statistics

### ISSUE THREAD

**Issue by jaimeventura** [telefonicaid/fiware-orion#3805] opened 2021-03-10 00:53 UTC
I've started an instance of orion with "-statCounters", and all i can get is:

```
"counters": {
"jsonRequests": 17777,
"batchUpdateRequests": 17777,
"versionRequests": 439,
"statisticsRequests": 13,
"invalidRequests": 24
},
```

Despite i did several operations ( getting entities, performing queries, creating subscriptions...)  i couldn't get stats for those.
 
Im currently using orion 2.4.2, but i have also tested with 2.3.0 and 2.5.2.
Am i missing something?

**Comment by fgalan** [comment] 2021-03-10 07:20
I'm afraid I don't fully understand the problem you describe...

Let's try to be precise, in the following way:

* How do you exactly start ContextBroker (i.e. `ps ax | grep contextBroker`)?
* Which request do you do once it has started? Preferred reporting way: curl statements
* Which request do you do to get statistics? Which result do you get? Which result do you expect?

Thanks!

**Comment by jaimeventura** [comment] 2021-03-10 10:21
Hey, thank you for the quick reply.
So, my expectations were to have statistics  on the number of operations. Actually, i took a sneak peek on the source code ([src/lib/serviceRoutines/statisticsTreat.cpp](https://github.com/telefonicaid/fiware-orion/blob/2.4.2/src/lib/serviceRoutines/statisticsTreat.cpp)) and found a lot of interesting counters.
My goal, beyond the obvious, is to have these into prometheus.

>How do you exactly start ContextBroker (i.e. ps ax | grep contextBroker)?

I started an instance with docker compose. Here's the orion service config:
```
   orion:
     #image: fiware/orion
     image: fiware/orion:2.4.2
     restart: unless-stopped
     ports:
       - "1026:1026"
     links:
       - mongo
     volumes:
       - /etc/pki/ca-trust:/etc/pki/ca-trust:ro
     command: -statCounters -statSemWait -statTiming -statNotifQueue -dbhost mongo -httpTimeout 10000
     logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
     healthcheck:
        test: curl --fail -s http://orion:1026/version || exit 1
        interval: 5s
```
>Which request do you do once it has started? Preferred reporting way: curl statements

This allows me to see the statistics.
```
$ curl localhost:1026/statistics
```

This would create a subscription (my expectation would be to have a `subscriptions´ counter, as implemented [here](https://github.com/telefonicaid/fiware-orion/blob/6eddd72022de1d43a41834527478242bb4d37bc5/src/lib/serviceRoutines/statisticsTreat.cpp#L184)).
```
$ curl --request POST   --url http://localhost:1026/v2/subscriptions   --header 'content-type: application/json'   --data '
{
  "description": "Vehicle for QuantumLeap DEV",
  "subject": {
    "entities": [{
        "idPattern": "urn:ngsi-ld:EVChargingStation",
        "type": "Device"
    }
    ]
  },
  "notification": {
    "http": {
      "url": "http://localhost:8668/v2/notify"
    }
  },
  "expires": "2118-06-10T20:00:00.00Z"
}
'
```

This would query orion for a specific entity. I could also query orion to get all entities and this would be another query that should increase the 'query' [counter](https://github.com/telefonicaid/fiware-orion/blob/6eddd72022de1d43a41834527478242bb4d37bc5/src/lib/serviceRoutines/statisticsTreat.cpp#L182). 
```
$ curl -s localhost:1026//v2/entities/urn:ngsi-ld:EVChargingStation:porto:1 | python -mjson.tool
{
    "allowedVehicleType": {
        "metadata": {},
        "type": "Array",
        "value": [
            "bicycle",
            "bus",
            "car"
        ]
    },
    "capacity": {
        "metadata": {},
        "type": "Number",
        "value": 100
    },
    "description": {
        "metadata": {},
        "type": "Text",
        "value": "teste charging station"
    },
    "id": "urn:ngsi-ld:EVChargingStation:porto:1",
    "location": {
        "metadata": {},
        "type": "geo:json",
        "value": {
            "coordinates": [
                -8.6052,
                41.18022
            ],
            "type": "Point"
        }
    },
    "name": {
        "metadata": {},
        "type": "Text",
        "value": "teste"
    },
    "socketType": {
        "metadata": {},
        "type": "Array",
        "value": [
            "Type3"
        ]
    },
    "type": "EVChargingStation"
}
```

Or, having the same  result but using the "q=" form of query/filter:
```
$ curl -s localhost:1026/v2/entities?q=name==teste | python -mjson.tool
[
    {
        "allowedVehicleType": {
            "metadata": {},
            "type": "Array",
            "value": [
                "bicycle",
                "bus",
                "car"
            ]
        },
        "capacity": {
            "metadata": {},
            "type": "Number",
            "value": 100
        },
        "description": {
            "metadata": {},
            "type": "Text",
            "value": "teste charging station"
        },
        "id": "urn:ngsi-ld:EVChargingStation:porto:1",
        "location": {
            "metadata": {},
            "type": "geo:json",
            "value": {
                "coordinates": [
                    -8.6052,
                    41.18022
                ],
                "type": "Point"
            }
        },
        "name": {
            "metadata": {},
            "type": "Text",
            "value": "teste"
        },
        "socketType": {
            "metadata": {},
            "type": "Array",
            "value": [
                "Type3"
            ]
        },
        "type": "EVChargingStation"
    }
]
```

Here, im performing an update on the entity. So my expectation would be to see a 'updates' [counter](https://github.com/telefonicaid/fiware-orion/blob/6eddd72022de1d43a41834527478242bb4d37bc5/src/lib/serviceRoutines/statisticsTreat.cpp#L183).
 
```
$ curl localhost:1026/v2/entities/urn:ngsi-ld:EVChargingStation:porto:1/attrs -s -S --header 'Content-Type: application/json' \
     -X PATCH -d @- <<EOF
{
  "name": {
    "value": "myNewName",
    "type": "Text"
  }
}
EOF
```



>Which request do you do to get statistics? Which result do you get? Which result do you expect?

Here's what i get if hit the /statistics endpoint
```
$ curl -s localhost:1026/statistics | python -mjson.tool
{
    "counters": {
        "batchUpdateRequests": 543932,
        "invalidRequests": 35,
        "jsonRequests": 543928,
        "statisticsRequests": 21,
        "versionRequests": 6704
    },
    "measuring_interval_in_secs": 34559,
    "semWait": {
        "connectionContext": 0,
        "dbConnectionPool": 0.242527932,
        "metrics": 0.197744995,
        "request": 73347.265625,
        "subCache": 0.311656207,
        "timeStat": 0.142325953,
        "transaction": 0.24053587
    },
    "timing": {
        "accumulated": {
            "jsonV2Parse": 49.676616669,
            "mongoBackend": 73535.6796875,
            "mongoCommandWait": 0.136287794,
            "mongoReadWait": 9061.96875,
            "mongoWriteWait": 2582.133789062,
            "render": 73.173576355,
            "total": 85464.046875
        },
        "last": {
            "jsonV2Parse": 6.5789e-05,
            "mongoBackend": 0.016188907,
            "mongoReadWait": 0.014807364,
            "mongoWriteWait": 0.001111389,
            "render": 6.7748e-05,
            "total": 0.01657344
        }
    },
    "uptime_in_secs": 34559
}
```

About my expectations, i believe i already mentioned them before. Referring to the documentation, i was expecting something as describe [there](https://fiware-orion.readthedocs.io/en/master/admin/statistics/index.html):
```
{
  ...
  "counters" : {
    "jsonRequests" : 75916,
    "queries" : 3698,           <----------------------
    "updates" : 2416,           <----------------------
    "subscriptions" : 138,    <----------------------
    "registrationRequest": 11,
    "registrations": 41,
    "unsubscriptions" : 6,
    "notificationsReceived" : 216936,
    "notificationsSent" : 579542,
    "individualContextEntity" : 360,
    "allContextEntitiesRequests" : 3,
    "versionRequests" : 1109,
    "statisticsRequests" : 13,
    "invalidRequests" : 2
  },
  ...
}

```

Thank you for your attention.

**Comment by jaimeventura** [comment] 2021-05-03 09:14
Hey @fgalan, sorry for bothering you.
Any news on this? Is there additional info you need?
Thank you,

**Comment by fgalan** [comment] 2021-05-19 11:20
I have been having a look to this and the problem is that statistics logic (statisticsUpdate() and renderCounterStats() mainly). The original counters came from the times of NGSIv1 which is now deprecated and it seems that NGSIv2 support is pretty irregular.

Thus, I think this has to be reworked, in the following way:

* All NGSIv1 requests will be aggregated under the same counter no matter its type, eg. `legacyNgsiv1`
* Re-define a set of counters aligned with the different operations in NGSIv2, at two levels, URL+VERB. For instance, URLs representing entities (`/v2/entities/<id>/attrs`) support different operations (POST, PUT, PATCH, GET) so we can have something like this:

```
"entityRequest": {
  "PATCH": 123,
  "PUT": 1243,
  "GET": 125432,
  "POST": 1214
}
``` 

With regards to second item, we have in fact a FIXME mark about it in renderCounterStats() function:

```
// FIXME: try to chose names closer to the ones used in API URLs
```

@jaimeventura as user of this feature, what do you think? Any additional suggestion?

**Comment by fgalan** [comment] 2021-05-19 11:31
Looking to the NGSIv2 spec we have the following:

* API entry point (/v2, suggested counter: "entryPoint")
* Entities (/v2/entities, suggested counter: "entities")
    * GET
    * POST
* Entity (/v2/entities/{id}, suggested counter: "entity")
    * GET
    * POST
    * DELETE
* Entity attributes (/v2/entities/{id}/attrs, suggested counter: "entityAttributes")
    * GET 
    * POST
    * PATCH
    * PUT
* Attribute (/v2/entities/{id}/attrs/{attr}, suggested counter "attribute")
    * GET
    * PUT
    * DELETE
* Attribute value (/v2/entities/{id}/attrs/{attr}/value, suggested counter "attributeValue")
    * GET
    * PUT
* Entity types (/v2/types, suggested counter "entityType")
    *  GET
* Entity type (/v2/types/{type}, suggested counter "entityType")
    *  GET
* Subscriptions (/v2/subscriptions, suggested counter "subscriptions")
    * GET
    * POST
* Subscription (/v2/subscriptions/{id}, suggested counter "subscription")
    * GET
    * PATCH
    * DELETE
* Registrations (/v2/registrations, suggested counter "registrations")
    * GET
    * POST
* Registration (/v2/registration/{id}, suggested counter "registration")
    * GET
    * PATCH (*not supported yet, but the counter for it could be defined in the code*)
    * DELETE
* Batch update (/v2/op/update, suggested counter "batchUpdate")
    * POST
* Batch query (/v2/op/query suggested counter "batchQuery")
    * POST
* Notification (/v2/op/notify suggested counter "notification")
    * POST

**Comment by jaimeventura** [comment] 2021-05-19 23:47
Seems great having detailed statistics. 
Not sure about the impact on the performance. So maybe you could make this a config: to have counters 'per URL'(less detail) or 'per URL+VERB (more detail).
I would also suggest adding counters for failed requests.

**Comment by fgalan** [comment] 2021-05-20 07:06
> Not sure about the impact on the performance. So maybe you could make this a config: to have counters 'per URL'(less detail) or 'per URL+VERB (more detail).

I think that's too much detail and the performance difference between two cases probably is very slow. The `-statCounters` flag will select if CB has to take counter as a whole (less performance) or not (more performance).

>  I would also suggest adding counters for failed requests.

We will keep the current `""invalidRequests"` counter for that. In addition, probably we will add a new one for `"missedVerb"` (cases in which the URL is correct but the verb is not supported, i.e. `PATCH /v2/entities`)

**Comment by fgalan** [comment] 2021-05-20 11:27
PR #3855 

(Reopened, as documentation modifications are yet pending)

**Comment by fgalan** [comment] 2021-05-20 11:58
This is how it looks like now after the changes:

```
    "counters": {
        "invalidRequests": 1,
        "jsonRequests": 1,
        "noPayloadRequests": 68,
        "notificationsSent": 1,
        "requests": {
            "entities": {
                "GET": 56
            },
            "entity": {
                "GET": 2,
                "PATCH": 1
            },
            "entityTypes": {
                "GET": 1
            },
            "statistics": {
                "GET": 5
            },
            "subscription": {
                "GET": 1
            },
            "subscriptions": {
                "GET": 2
            }
        },
        "versionRequests": 0
    },
```

**Comment by fgalan** [comment] 2021-05-20 13:20
PR with documentation fixes: https://github.com/telefonicaid/fiware-orion/pull/3856

@jaimeventura you can use `fiware/orion:latest` and test the new implementation, please. We will leave this issue opened for a while waiting for your feedback.

**Comment by fgalan** [comment] 2021-06-09 11:37
Time enough has passed. Orion 3.1.0 has been released today, so we are going to close this issue.

However, if you have additional feedback @jaimeventura don't hesitate to post here, of course. The issue can be reopened or re-created if we need it.

**Closed by fgalan** 2021-06-09 11:37 UTC

**Comment by jaimeventura** [comment] 2021-06-15 15:55
Hey,
Sorry, i missed the latest reply. I'll check it anyway.
Thank you so much for the effort on this.
