### ISSUE TITLE
not able to connect to azure cosmos db 

### ISSUE THREAD

**Issue by krishnakant-mahamuni** [telefonicaid/fiware-orion#3797] opened 2021-03-08 00:12 UTC
Below is the YAML for the Orion, when I am trying to use Azure Cosmos DB Mongo API it fails with the below error, is there a way I can use any of the managed mongo DB instances with Orion? 
```

time=2021-03-05T04:05:45.784Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=safeMongo.cpp[360]:getField | msg=Runtime Error (field '_id' is missing in BSONObj <{ cursor: { id: 0, ns: "orion.csubs", firstBatch: [] }, ok: 1.0 }> from caller mongoSubCacheItemInsert:83)
time=2021-03-05T04:05:45.784Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=AlarmManager.cpp[211]:dbError | msg=Raising alarm DatabaseError: error retrieving _id field in doc: '{ cursor: { id: 0, ns: "orion.csubs", firstBatch: [] }, ok: 1.0 }

```
```
apiVersion: v1
kind: Namespace
metadata:
  name: fiware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion
  namespace: fiware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion
  template:
    metadata:
      labels:
        app: orion
    spec:
      containers:
      - name: orion
        image: fiware/orion:2.5.2
        ports:
        - containerPort: 1026
          name: http
          protocol: TCP
        args: ["-dbhost", "<<HOST HERE>>:<<PORT>>", "-db", "<<DB>>", "-dbuser", "<<USER>>", "-dbpwd","<<PWD>>", "-dbSSL", "-rplSet","globaldb","-dbAuthDb","admin", "-httpTimeout","15000", "-logLevel", "INFO"]
---
apiVersion: v1
kind: Service
metadata:
  name: orion
  namespace: fiware
spec:
  selector:
    app: orion
  type: LoadBalancer
  ports:
    - port: 1026
      protocol: TCP
      targetPort: 1026
      nodePort: 30000
```

**Comment by fgalan** [comment] 2021-03-08 08:59
Seems to be similar to https://github.com/telefonicaid/fiware-orion/issues/3778

How var is Azure Cosmos DB Mongo API from a real MongoDB instance?

**Comment by fgalan** [comment] 2021-03-10 14:58
> Maybe the new mongo driver we are going to use in Orion for next release (work in progress in PR #3622) may work. There is an experimental docker version available and it would be great if you could test with it and tell us how it goes.
> 
> This is the image to use `telefonicaiot/fiware-orion:newdriver`
> 
> Thanks for the feedback!

Hold on... it seems there is some kind of problem with that image. I'll tell you when it gets ready again.

**Comment by krishnakant-mahamuni** [comment] 2021-03-11 04:11
works! with the new Image it connects to the cosmos DB instance and that is what I can test for. As I am not able to install any more dependencies to check our functionality.

docker build -t telefonicaiot/fiware-orion:gcversion .
[+] Building 1.1s (7/8)                                                                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 982B                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/telefonicaiot/fiware-orion:newdriver                                                                                                 0.0s
 => [internal] load build context                                                                                                                                               0.5s
 => => transferring context: 16.47MB                                                                                                                                            0.4s
 => [1/4] FROM docker.io/telefonicaiot/fiware-orion:newdriver                                                                                                                   0.0s
 => => resolve docker.io/telefonicaiot/fiware-orion:newdriver                                                                                                                   0.0s
 => [2/4] COPY ./opt /opt                                                                                                                                                       0.1s
 => ERROR [3/4] RUN cd /opt/orion/install/ && rpm -i mongodb-org-shell-3.6.19-1.el6.x86_64.rpm                                                                                  0.4s
------
 > [3/4] RUN cd /opt/orion/install/ && rpm -i mongodb-org-shell-3.6.19-1.el6.x86_64.rpm:
#5 0.308 warning: **mongodb-org-shell-3.6.19-1.el6.x86_64.rpm**: Header V3 RSA/SHA1 Signature, key ID 91fa4ad5: NOKEY
#5 0.329 error: Failed dependencies:
#5 0.329        libcrypto.so.10()(64bit) is needed by mongodb-org-shell-3.6.19-1.el6.x86_64
#5 0.329        libssl.so.10()(64bit) is needed by mongodb-org-shell-3.6.19-1.el6.x86_64
------
executor failed running [/bin/bash -o pipefail -c cd /opt/orion/install/ && rpm -i mongodb-org-shell-3.6.19-1.el6.x86_64.rpm]: exit code: 1 


my docker file

```
FROM telefonicaiot/fiware-orion:newdriver

# Data and scripts that can be used to seed the database at runtime:
COPY ./opt /opt

# Mongo 3.6 shell for CentOS 6.2+:
# From https://repo.mongodb.org/yum/redhat/6/mongodb-org/3.6/x86_64/RPMS/mongodb-org-shell-3.6.19-1.el6.x86_64.rpm
RUN cd /opt/orion/install/ && rpm -i mongodb-org-shell-3.6.19-1.el6.x86_64.rpm

# jq 1.6:
# From https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
RUN cp /opt/orion/install/jq-linux64-1.6 /usr/bin/jq && chmod a+x /usr/bin/jq

EXPOSE 1026

ENTRYPOINT /usr/bin/contextBroker -fg -multiservice
```

**Comment by fgalan** [comment] 2021-03-11 08:00
Related question at SOF: https://stackoverflow.com/questions/66486767/using-fiware-orion-with-azure-cosmos-db-mongo-api

**Comment by fgalan** [comment] 2021-03-11 08:01
> works!

Good news! :)

So I understand this issue can be closed when the Orion version with the new driver (expected for version 3.0.0) will be released. I understand the problems with your docker setup are out of the scope of this issue (whic is about Orion connecting to Cosmos DB).

**Comment by krishnakant-mahamuni** [comment] 2021-03-12 11:38
sorry. it actually does not work. when I am running a container with a new image the logs say the container is connected to the cosmos instance but when I 

curl localhost:1026/version I am getting errors 

`kubectl get pods`

NAME                     READY   STATUS    RESTARTS   AGE
orion-55d689c589-h78kq   1/1     Running   0          2m21s

`kubectl logs orion-55d689c589-h78kq`

time=2021-03-12T11:27:39.229Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[1000]:main | msg=start command line </usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -disableFileLog -dbhost <<HOST HERE>> -port 10255 -db oriondb -dbuser <<USER NAME HERE>> -dbpwd <<PASSWORD HERE>> -dbSSL -httpTimeout 15000 -logLevel INFO>
time=2021-03-12T11:27:39.229Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[1068]:main | msg=**Orion Context Broker is running**

`kubectl exec orion-55d689c589-h78kq -it /bin/bash`

kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.

`bash-4.4$ curl localhost:1026/version`

**curl: (7) Failed to connect to localhost port 1026: Connection refused**

**Comment by fgalan** [comment] 2021-03-15 11:52
We need to distinghish between two possible errores:

A. Orion cannot connect to Azure Cosmos DB
B. Problems with the k8s deployment

By [your previos report](https://github.com/telefonicaid/fiware-orion/issues/3797#issuecomment-796433160) I understand item A is fixed. However, I'd suggest the following test to be fully sure:

1. Use the following docker-compose file:

```
version: "3" 

services:
  orion:
    image: telefonicaiot/fiware-orion:newdriver
    ports:
      - "1026:1026"
    command: -dbhost <<HOST HERE>>:<<PORT>>
```


2. Run it with:

```
docker-compose up
```

4. Test it with:

```
curl localhost:1026/version
curl localhost:1025/v2/entities
```

Could you do the test (in some place with docker installed and able to connect to you Azure Cosmos DB instance) and tell us how it goes, please? Thanks!

**Comment by fgalan** [comment] 2021-03-15 11:56
Alternatively, I could do the test but I'd need the HOST, PORT, USER, PSW info. Maybe we can found some private channel to pass it to me.

**Comment by krishnakant-mahamuni** [comment] 2021-03-15 12:12
> Alternatively, I could do the test but I'd need the HOST, PORT, USER, PWD info. Maybe we can found some private channel to pass it to me.

I tried with docker-compose 


curl: (52) Empty reply from server


sure, let me know your email ID I will send the details.

**Comment by fgalan** [comment] 2021-03-15 12:14
> sure, let me know your email ID I will send the details.

I cannot post it here as it is a public place ;)

Maybe you have the contact from somebody in the FIWARE Foundation? They know who I am and could provide you my email.

**Comment by krishnakant-mahamuni** [comment] 2021-03-15 12:25
> Maybe you have the contact from somebody in the FIWARE Foundation? They know who I am and could provide you my email.

can you email me on krishnakant.mahamuni@gmail.com

**Comment by fgalan** [comment] 2021-03-17 13:36
I have done some progress.

There were two problems:

* The password you are using is very long and the code was not prepared for that. I have modified the code to extend the supported length (from 63 to 255).
* Azure Cosmos DB is not compatible with retry writes (maybe the version is too old?). A new CLI flag has been created (`-dbDisableRetryWrites`) to set this.

Once done that (new `telefonicaiot/fiware-orion:newdriver` container available) and using the following docker-compose.yml (obfuscated):

```
version: "3"

services:
  orion:
    image: telefonicaiot/fiware-orion:newdriver
    ports:
      - "1026:1026"
    command: -dbhost "..." -db "oriondb" -dbuser "..." -dbpwd "..." -dbSSL -dbDisableRetryWrites -logLevel DEBUG -t 100
```

it works. This is the `docker-compose up` trace (obfuscated):

```
orion_1  | time=2021-03-17T13:27:45.704Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[1012]:main | msg=start command line </usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -disableFileLog -dbhost ... -db oriondb -dbuser ... -dbpwd ****** -dbSSL -dbDisableRetryWrites -logLevel DEBUG -t 100>
orion_1  | time=2021-03-17T13:27:45.704Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[1080]:main | msg=Orion Context Broker is running
orion_1  | time=2021-03-17T13:27:45.709Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[375]:composeMongoUri | msg=MongoDB connection URI: 'mongodb:/.../?tls=true&tlsAllowInvalidCertificates=true&retryWrites=false&connectTimeoutMS=10000'
orion_1  | time=2021-03-17T13:27:49.286Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[239]:mongoConnect | msg=connection created with Write Concern: 1
orion_1  | time=2021-03-17T13:27:51.956Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[239]:mongoConnect | msg=connection created with Write Concern: 1
orion_1  | time=2021-03-17T13:27:54.901Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[239]:mongoConnect | msg=connection created with Write Concern: 1
orion_1  | time=2021-03-17T13:27:58.351Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[239]:mongoConnect | msg=connection created with Write Concern: 1
orion_1  | time=2021-03-17T13:28:01.022Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[239]:mongoConnect | msg=connection created with Write Concern: 1
orion_1  | time=2021-03-17T13:28:03.665Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[239]:mongoConnect | msg=connection created with Write Concern: 1
orion_1  | time=2021-03-17T13:28:06.460Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[239]:mongoConnect | msg=connection created with Write Concern: 1
orion_1  | time=2021-03-17T13:28:09.102Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[239]:mongoConnect | msg=connection created with Write Concern: 1
orion_1  | time=2021-03-17T13:28:11.868Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[239]:mongoConnect | msg=connection created with Write Concern: 1
orion_1  | time=2021-03-17T13:28:14.667Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[239]:mongoConnect | msg=connection created with Write Concern: 1
orion_1  | time=2021-03-17T13:28:14.667Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[692]:runDatabaseCommand | msg=runCommand() in 'admin' database: '{ "buildinfo" : 1 }'
orion_1  | time=2021-03-17T13:28:15.309Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[497]:mongoConnectionPoolInit | msg=mongo version server: 3.6.0 (mayor: 3, minor: 6, extra: 0)
orion_1  | time=2021-03-17T13:28:15.310Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[499]:mongoConnectionPoolInit | msg=Connected to mongodb://.../?tls=true&tlsAllowInvalidCertificates=true&retryWrites=false&connectTimeoutMS=10000 (dbName: oriondb, poolsize: 10)
orion_1  | time=2021-03-17T13:28:15.310Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[692]:runDatabaseCommand | msg=runCommand() in 'admin' database: '{ "listDatabases" : 1 }'
orion_1  | time=2021-03-17T13:28:15.637Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[692]:runDatabaseCommand | msg=runCommand() in 'admin' database: '{ "listDatabases" : 1 }'
orion_1  | time=2021-03-17T13:28:15.963Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=MongoGlobal.cpp[375]:tenantFromDb | msg=DB -> tenant: <oriondb> -> <>
orion_1  | time=2021-03-17T13:28:15.963Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[76]:collectionQuery | msg=query() in 'oriondb.csubs' collection: '{ }'
orion_1  | time=2021-03-17T13:28:16.323Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[1206]:main | msg=Startup completed
```

Once it has started, I have tested to create an entity in the "foo" service:

```
curl localhost:1026/v2/entities -s -S -H 'fiware-service: foo' -H 'Content-Type: application/json' -d @- <<EOF
{
  "id": "E",
  "type": "T",
  "msg": {
    "value": "It works",
    "type": "Text"
  }
}
EOF
```

And accessing with mongo shell the entity is there:

```
globaldb:PRIMARY> use oriondb-foo
switched to db oriondb-foo
globaldb:PRIMARY> db.entities.find().pretty()
{
	"_id" : {
		"id" : "E",
		"type" : "T",
		"servicePath" : "/"
	},
	"attrNames" : [
		"msg"
	],
	"attrs" : {
		"msg" : {
			"type" : "Text",
			"creDate" : 1615987809.2889066,
			"modDate" : 1615987809.2889066,
			"value" : "It works",
			"mdNames" : [ ]
		}
	},
	"creDate" : 1615987809.2889066,
	"modDate" : 1615987809.2889066,
	"lastCorrelator" : "e3ac840c-8724-11eb-9995-0242ac140002"
}
```

The problem now is with query operation:

```
curl localhost:1026/v2/entities -s -S -H 'fiware-service: foo' | python -mjson.tool
```

It doesn't return the above entity and the following is seen in the logs:

```
orion_1  | time=2021-03-17T13:32:05.042Z | lvl=ERROR | corr=2973804e-8725-11eb-89f9-0242ac140002 | trans=1615987665-703-00000000004 | from=172.20.0.1 | srv=foo | subsrv=<none> | comp=Orion | op=MongoGlobal.cpp[1713]:entitiesQuery | msg=Runtime Error (exception in next(): Error at querying MongoDB - query: { })
```

Please don't remove the `orion-foo` DB by the moment while I'm still testing.

**Comment by krishnakant-mahamuni** [comment] 2021-03-17 22:12
> Please don't remove the `orion-foo` DB by the moment while I'm still testing.

Thank you. Great progress will await your next update.

**Comment by fgalan** [comment] 2021-03-18 16:13
After some improvements in commit https://github.com/telefonicaid/fiware-orion/pull/3622/commits/dd35aa62382845c58a9bcdf636c9335c51494523 to provide error responses in situations like this, the response to 

```
curl -vvvv -H 'fiware-service: foo' localhost:1026/v2/entities
```

is

```
< HTTP/1.1 500 Internal Server Error
< Connection: Keep-Alive
< Content-Length: 679
< Content-Type: application/json
< Fiware-Correlator: ce0e5876-87fd-11eb-953d-000c29df7908
< Date: Thu, 18 Mar 2021 15:22:56 GMT
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
{"error":"Internal Server Error","description":"Error at querying MongoDB: Error&#61;2, Details&#61;&#39;Response status code does not indicate success: BadRequest &#40;400&#41;&#59; Substatus: 0&#59; ActivityId: a3e106b2-990f-4d61-81bc-966799d1b419&#59; Reason: &#40;Response status code does not indicate success: BadRequest &#40;400&#41;&#59; Substatus: 0&#59; ActivityId: a3e106b2-990f-4d61-81bc-966799d1b419&#59; Reason: &#40;Response status code does not indicate success: BadRequest &#40;400&#41;&#59; Substatus: 0&#59; ActivityId: a3e106b2-990f-4d61-81bc-966799d1b419&#59; Reason: &#40;Message: {&quot;Errors&quot;:[&quot;The index path corresponding to the specified o"}
```

which decoded payload is:

```
"Error at querying MongoDB: Error=2, Details='Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: f3ab9bbf-da1f-42ac-8b05-e1e70660cafa; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: f3ab9bbf-da1f-42ac-8b05-e1e70660cafa; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: f3ab9bbf-da1f-42ac-8b05-e1e70660cafa; Reason: (Message: {"Errors":["The index path corresponding to the specified o"}
```

The MongoDB driver truncates errors when they are too long. However, googling arround it seems the full error message is `"The index path corresponding to the specified order-by item is excluded"`.

Looking to https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-troubleshoot it seems that when a query uses sorting, it needs an index matching the sort statement. By default Orion orders by creation date so the following index needs to be created in `orion-foo` database:

```
db.entities.createIndex({creDate:1})
```

After running that comment, the above curl now works:

```
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 78
< Content-Type: application/json
< Fiware-Correlator: a22b937a-87ff-11eb-9d38-000c29df7908
< Date: Thu, 18 Mar 2021 15:35:58 GMT
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
[{"id":"E","type":"T","msg":{"type":"Text","value":"It works","metadata":{}}}]
```

You can now remove the `oriondb-foo` database in your cluster and try to reproduce the same steps yourself with the last version of `:newdriver` containner and the docker-compose.yml above. Please, provide feedback about how it goes.

**Comment by fgalan** [comment] 2021-03-18 16:17
> it seems that when a query uses sorting, it needs an index matching the sort statement. By default Orion orders by creation date so the following index needs to be created in `orion-foo` database:
> 
> ```
> db.entities.createIndex({creDate:1})
> ```

Side note: `creDate` is used when no `orderBy` is used in the request, i.e. `GET /v2/entities`. However, if you use an explicit `orderBy` like `GET /v2/entities?orderBy=A` you would need an index for that or you will get a similar 500 Internal Server error. This [documentation](https://fiware-orion.readthedocs.io/en/master/admin/perf_tuning/index.html#database-indexes) explain the indexes needed for optimizing this kind of queries (with the different than in Cosmos DB it seems it is not a matter of optimization but a requirement of the DB).

**Comment by fgalan** [comment] 2021-03-18 16:19
Side note2: you will see this trace on the logs:

```
orion_1  | time=2021-03-18T15:47:22.250Z | lvl=ERROR | corr=391a76ec-8801-11eb-9ec6-0242ac160002 | trans=1616082335-577-00000000001 | from=172.22.0.1 | srv=foo | subsrv=<none> | comp=Orion | op=AlarmManager.cpp[211]:dbError | msg=Raising alarm DatabaseError: collection: oriondb-foo.entities - runCommand(): { "createIndexes" : "entities", "indexes" : [ { "key" : { "expDate" : 1 }, "name" : "expDate_1", "expireAfterSeconds" : 0 } ] } - exception: The 'expireAfterSeconds' option is supported on '_ts' field only.
```

Due to this limitation in CosmosDB the feature of [transient entities](https://fiware-orion.readthedocs.io/en/master/user/transient_entities/index.html) will not work.

**Comment by krishnakant-mahamuni** [comment] 2021-03-24 05:41
Apologies it took a little time to get back, I have tested the current solution using docker-compose and also with Kubernetes manifest. Initially, things are looking good. I will do few more tests before I can say everything is working fine, this should be done soon. Thanks again Fermin.

**Comment by fgalan** [comment] 2021-03-24 13:24
Thanks for the feedback. Let's keep the issue openen until #3622 gets merged in master. I'll answer the question in SOF too when that happens.

**Comment by fgalan** [comment] 2021-04-09 16:34
> This is the image to use telefonicaiot/fiware-orion:newdriver

PR #3622 has been merged into master. Thus, we can use `:latest` from now on. In fact, `:newdriver` label will be removed from dockerhub.

**Closed** 2021-04-12 07:22 UTC

**Comment by anupamme** [comment] 2022-04-26 05:26
Hello

I tried using azure cosmos db and I am running into some issues so I am re-opening this issue. If I need to open a separate issue then please let me know.

I'm using the following docker-compose.yml:

` version: "3" 

 services:
   orion:
     image: fiware/orion
     ports:
       - "1026:1026"
     command: -dbhost "mongo-perf-testing.mongo.cosmos.azure.com:10255" -db "fiver_db" -dbuser "mongo-perf-testing" -dbpwd "vUcNuAU3nvhifP3cGsgx3HjTuX3seqq6CA6jHO9OlQfktfP5G8eG4FSeJKBPv89F5ydKxsnhtSstRuJKSDDFJg==" -dbSSL -dbDisableRetryWrites -logLevel DEBUG -t 100`

When I run the docker container, it starts off okay. 

Then I run following queries:

Query: `curl localhost:1026/version`
Response: 
`{
"orion" : {
  "version" : "3.6.0",
  "uptime" : "0 d, 0 h, 9 m, 31 s",
  "git_hash" : "973850279e63d58cb93dff751648af5ec6e05777",
  "compile_time" : "Wed Mar 2 10:34:48 UTC 2022",
  "compiled_by" : "root",
  "compiled_in" : "5e6b6f1167f7",
  "release_date" : "Wed Mar 2 10:34:48 UTC 2022",
  "machine" : "x86_64",
  "doc" : "https://fiware-orion.rtfd.io/en/3.6.0/",
  "libversions": {
     "boost": "1_66",
     "libcurl": "libcurl/7.61.1 OpenSSL/1.1.1k zlib/1.2.11 nghttp2/1.33.0",
     "libmosquitto": "2.0.12",
     "libmicrohttpd": "0.9.70",
     "openssl": "1.1",
     "rapidjson": "1.1.0",
     "mongoc": "1.17.4",
     "bson": "1.17.4"
  }
}
}`

Then I insert an entry using following:
Q: `curl -iX POST \
  'http://localhost:1026/v2/entities' \
  -H 'Content-Type: application/json' \
  -d '
{
    "id": "urn:ngsi-ld:Store:001",
    "type": "Store",
    "address": {
        "type": "PostalAddress",
        "value": {
            "streetAddress": "Bornholmer Straße 65",
            "addressRegion": "Berlin",
            "addressLocality": "Prenzlauer Berg",
            "postalCode": "10439"
        },
        "metadata": {
            "verified": {
                "value": true,
                "type": "Boolean"
            }
        }
    },
    "location": {
        "type": "geo:json",
        "value": {
             "type": "Point",
             "coordinates": [13.3986, 52.5547]
        }
    },
    "name": {
        "type": "Text",
        "value": "Bösebrücke Einkauf"
    }
}'`

Response:
`HTTP/1.1 201 Created
Connection: Keep-Alive
Content-Length: 0
Location: /v2/entities/urn:ngsi-ld:Store:003?type=Store
Fiware-Correlator: f32e6e46-c520-11ec-b804-0242ac130002`

Now the problematic part:
Q: `curl -G -X GET \
    'http://localhost:1026/v2/entities' \
    -d 'type=Store' \
    -d 'options=keyValues'`

R: `{"error":"Internal Server Error","description":"Error at querying MongoDB: Error&#61;2, Details&#61;&#39;Response status code does not indicate success: BadRequest &#40;400&#41;&#59; Substatus: 0&#59; ActivityId: fde36487-2dd9-44a4-a719-99453acdd618&#59; Reason: &#40;Response status code does not indicate success: BadRequest &#40;400&#41;&#59; Substatus: 0&#59; ActivityId: fde36487-2dd9-44a4-a719-99453acdd618&#59; Reason: &#40;Response status code does not indicate success: BadRequest &#40;400&#41;&#59; Substatus: 0&#59; ActivityId: fde36487-2dd9-44a4-a719-99453acdd618&#59; Reason: &#40;Message: {&quot;Errors&quot;:[&quot;The index path corresponding to the specified o"}`

When I goto Azure cosmosdb dashboard I can see the entry present. So I am not sure what is going wrong here.

Can you please suggest how to fix this issue?

**Comment by fgalan** [comment] 2022-04-28 15:16
> Can you please suggest how to fix this issue?

@anupamme I'd suggest to post your question at StackOverflow (https://stackoverflow.com, using "fiware-orion" label). Note the issue is closed and your question seems to be more related with a support case than with an actual issue in the software (of course if after discussing your question at SOF some issue is detected in Orion, we'll create the proper issue in this repository).

Once you have created the question at SOF, please add the link as a new comment here, for reference.

Thanks!

**Comment by anupamme** [comment] 2022-04-29 05:38
@fgalan here is the question at SOF:

https://stackoverflow.com/questions/72053276/connecting-fiware-orion-with-azure-cosmos-db

**Comment by anupamme** [comment] 2022-05-05 04:49
@fgalan I can privately send you credentials for the Cosmos DB Mongo API so that you can test it for yourself as well, if it helps in your understanding.

**Comment by fgalan** [comment] 2022-05-05 08:02
> @fgalan I can privately send you credentials for the Cosmos DB Mongo API so that you can test it for yourself as well, if it helps in your understanding.

Sure? As far as I read in https://stackoverflow.com/questions/72053276/connecting-fiware-orion-with-azure-cosmos-db you finally solved the problem...

**Comment by anupamme** [comment] 2022-05-05 08:39
Yes, I did. I wrote this comment before I read your message at SOF.

**Comment by anupamme** [comment] 2022-05-27 06:10
Hello @fgalan 

We would like to add to the documentation on how to integrate Cosmos DB with Fiware Orion. So that anyone (who wants to use Cosmos DB) can read the documentation rather than follow along this issue or the SOF issue.

So which places at the repository would be the correct place for making these changes?

One place I found is this: https://github.com/telefonicaid/fiware-orion/blob/master/docker/README.md

Once I hear from you, I will be more than glad to send you the pull requests with these changes.

If you see any issue in this then please let me know.

**Comment by mapedraza** [comment] 2022-05-27 09:36
Good idea @anupamme 

The best path to place the document is onto [`doc/manuals/admin/extra`](https://github.com/telefonicaid/fiware-orion/tree/master/doc/manuals/admin/extra) folder.
