### ISSUE TITLE
Possible bug detected about patterned subscriptions [cache not working]

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1308] opened 2015-10-01 09:58 UTC
The following subscription seems to have stopped working in 0.24.0. It worked in 0.23.0, prior to the Subscription Cache implementation:

    {
      "entities": [
        {
          "type": "device",
          "isPattern": "true",
          "id": ".*”
        }
      ],
      "reference": "{{endpoint}}",
      "duration": "P1D",
      "notifyConditions": [
        {
          "type": "ONCHANGE",
          "condValues": [ "h" ]
        }
      ]
    }

The expected notifications no longer arrive.
If the Subscription is modified to use an exact **entity::id** (e.g. "id": "E1", and isPattern == false) instead of **.***, then everything works as before.
Reported by @antoniojoseln, Sep 9, 2015

**Comment by fgalan** [comment] 2015-10-01 10:43
> If the Subscription is modified to use the exact entity::id instead of .*, then everything works as before.

You mean that it works with <id="entityId", isPattern="true"> or with <id="entityId", isPattern="false">? A subtle but important detail that may help to debug the issue...

**Comment by kzangeli** [comment] 2015-10-01 10:53
Yes, it was not 100% clear, perhaps.
I edited the initial description to include "isPattern": "false".

**Comment by kzangeli** [comment] 2015-10-01 10:55
However, the simple functest I created to try to reproduce the bug **did not** reproduce the bug.
It worked just the way it should ...
We need to compare my test case to the real test case, the one that has the problem of not being notified.

**Comment by kzangeli** [comment] 2015-10-07 07:09
Found the problem, I believe.
tenantFromDb() in MongoGlobal.cpp **always** returns "" (empty string).

[ This function is only used by the subscription cache ]

**Comment by fgalan** [comment] 2015-10-14 09:03
After working on this issue in deep, it seems that the problem is more complex. After fixing tenantFromDB(), the whole list of tenant is processes. This "open" a new bug, found in some environment (Integration) with around 40 tenant, some of them with more that 800 subscriptions.

In this situation, it seems that the cache logic (maybe related with concurrent write access to the cache table) corrupt memory and eventually crash the broker.

**Comment by dmabtrg** [comment] 2015-10-26 14:49
I'm testing with the latest docker image from dockerhub (https://hub.docker.com/r/fiware/orion/builds/brtokibglv829ensgaxbsfg/) and I see no notifications sent from orion.  This is the payload we're using to generate the subscription:
```
{
    "entities": [
        {
            "type": "thing",
            "isPattern": "true",
            "id": "SENSOR_TEMP_*"
        }
    ],
    "attributes": [
        "temperature"
    ],
    "reference": "${DEVGUIDE_URL}",
    "duration": "P1M",
    "notifyConditions": [
        {
            "type": "ONCHANGE",
            "condValues": [
                "TimeInstant"
            ]
        }
    ],
    "throttling": "PT1S"
}
```

The value of `DEVGUIDE_URL` is set by the script that generates the subscriptions.

**Comment by dmabtrg** [comment] 2015-10-26 16:13
Ok, here's more info on our test case.

 We are using orion as contextBroker for both IDAS and our application (see [fiware-devguide-app](https://github.com/Bitergia/fiware-devguide-app) repository).  For IDAS we are setting both Fiware-Service and Fiware-ServicePath, but not for our application, so with orion running now in multiservice mode, all IDAS data goes to a different database.  Our subscription was not setting the Fiware-Service and Fiware-ServicePath headers, so there was no entities matching on the default database.  That solves one problem.

Now that the subscription is looking for entities on the right database, orion generates _some_ notifications, but not all.  We have a docker container with a ultralight client for idas that generates several sensors and periodically send updates to idas.  In this case, Fiware-Service is `devguideiot` and Fiware-ServicePath is `/`.  If we subscribe to this sensors (using the payload from my previous comment) we receive an initial notification containing all the sensors data.  After that, every time the sensors are updated (at almost the same time) orion only sends a single notification with the update of only one sensor (usually the first one).  No notification is generated for the other sensors.

**Comment by dmabtrg** [comment] 2015-10-26 17:13
After removing
```
 "throttling": "PT1S"
```
from the payload, all notifications are sent.

So, Fiware-Service and Fiware-ServicePath are needed when using orion in multiservice mode and throttling can cause some of the notifications to get lost.

**Comment by fgalan** [comment] 2015-10-28 16:44
Testing in Jose Rodriguez testbed, it works with: 0.24.0_20151027095932 (git version: ae1514eac417823a5e5aa53387101a7b2629d396)

**Comment by fgalan** [comment] 2015-11-02 07:45
I understand that this has been finally fixed in 0.25.0 so now (at 0.25.0 releasing date), I'm closing this issue.

**Comment by kzangeli** [comment] 2015-11-04 14:16
New info on this issue, testing in the QA machine qa-orion-fe-01:

The test fails **only** if we use sub-cache-refresh *and* subscription-update.

sub-cache-refresh is only interesting for **active-active** and subscription-update is not really interesting at all.

NOTE:
After sub-update, the **first** notification (sometimes 2 notifications) arrives, so, it seems it is the cache-refresh that "destroys" the subscription.
A test with sub-cache-refresh-interval of 1000 secs just verified this hypothesis.

**Comment by fgalan** [comment] 2015-11-04 22:06
This issue is about the "big crash" of the cache (fortunatelly solved). So, it is better to keep it closed. New information has been moved to the "continuation" issue at https://github.com/telefonicaid/fiware-orion/issues/1406#issuecomment-153883697

**Closed by fgalan** 2015-11-04 22:06 UTC
Labels: bug, P4
